# Generated by Django 6.0.3 on 2026-04-28 19:18

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_footerlink_page_remove_navbarbutton_page_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image_main',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_main', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image_video_thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_image_video_thumb', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_mission_icon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_mission_icon', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_mission_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_video_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='benefits_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='blog_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='courses_subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='courses_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_about_text',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_about_title',
            field=models.CharField(default='About Us', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_contact_address',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_contact_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_contact_map_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_contact_phone',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_contact_title',
            field=models.CharField(default='Contact Us', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_copyright_text',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_explore_title',
            field=models.CharField(default='Explore', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_links_title',
            field=models.CharField(default='Useful Links', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='footer_logo_img', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='footer_newsletter_heading',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepage',
            name='journey_btn_label',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='journey_btn_url',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='journey_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journey_logo_image', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='journey_subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='journey_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_subtitle',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='homepage',
            name='testimonials_title',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.CreateModel(
            name='AboutFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=300)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_features', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BenefitCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('counter', models.CharField(help_text='e.g. "95"', max_length=20)),
                ('suffix', models.CharField(blank=True, help_text='e.g. "%", "+"', max_length=5)),
                ('label', models.CharField(max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField()),
                ('url', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_post_image', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CourseCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('tab', models.CharField(choices=[('all', 'All'), ('design', 'Design'), ('data-science', 'Data Science'), ('marketing', 'Marketing'), ('development', 'Development')], default='all', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('lessons_count', models.CharField(default='', help_text='e.g. "8 Lessons"', max_length=20)),
                ('students_count', models.CharField(default='', help_text='e.g. "70 Students"', max_length=20)),
                ('price', models.CharField(default='', help_text='e.g. "$87"', max_length=20)),
                ('modal_description', models.TextField(default='')),
                ('modal_btn_label', models.CharField(default='Read More', max_length=50)),
                ('modal_btn_url', models.CharField(default='', max_length=255)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_card_image', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_cards', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterExploreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_explore_links', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_social_links', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterUsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_useful_links', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Happy Client', max_length=100)),
                ('quote', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to='home.homepage')),
                ('photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonial_photo', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
