# Generated by Django 6.0.3 on 2026-05-01 18:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_about_description_homepage_about_image_main_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nav_phone', models.CharField(default='', max_length=30, verbose_name='Phone Number')),
                ('banner_title', models.CharField(default='Contact Us', max_length=200)),
                ('banner_description', models.TextField(default='')),
                ('contact_info_subtitle', models.CharField(default='Contact Info', max_length=100)),
                ('contact_info_title', models.CharField(default='Our Contact Information', max_length=200)),
                ('location_address', models.TextField(default='')),
                ('location_map_url', models.URLField(blank=True, verbose_name='Location Google Maps URL')),
                ('phone_1', models.CharField(default='', max_length=30)),
                ('phone_2', models.CharField(blank=True, default='', max_length=30)),
                ('email_1', models.EmailField(default='', max_length=254)),
                ('email_2', models.EmailField(blank=True, default='', max_length=254)),
                ('form_subtitle', models.CharField(default='Registration', max_length=100)),
                ('form_title', models.CharField(default='Register Your Free Account', max_length=200)),
                ('map_embed_url', models.URLField(blank=True, verbose_name='Google Maps Embed URL')),
                ('footer_newsletter_heading', models.CharField(default='Sign up for the newsletter:', max_length=200)),
                ('footer_about_title', models.CharField(default='About Us', max_length=100)),
                ('footer_about_text', models.TextField(default='')),
                ('footer_links_title', models.CharField(default='Useful Links', max_length=100)),
                ('footer_explore_title', models.CharField(default='Explore', max_length=100)),
                ('footer_contact_title', models.CharField(default='Contact Us', max_length=100)),
                ('footer_contact_phone', models.CharField(default='', max_length=30)),
                ('footer_contact_email', models.EmailField(default='', max_length=254)),
                ('footer_contact_address', models.CharField(default='', max_length=300)),
                ('footer_contact_map_url', models.URLField(blank=True)),
                ('footer_copyright_text', models.CharField(default='', max_length=200)),
                ('footer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_footer_logo', to='wagtailimages.image')),
                ('form_bg_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form_bg', to='wagtailimages.image', verbose_name='Form Left Background Image')),
                ('nav_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_nav_logo', to='wagtailimages.image', verbose_name='Navbar Logo')),
            ],
            options={
                'verbose_name': 'Contact Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactFooterUsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_footer_useful_links', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactFooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_footer_social_links', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactFooterExploreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_footer_explore_links', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
