# Generated by Django 6.0.3 on 2026-05-01 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactpage_contactfooterusefullink_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='banner_bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_banner_bg', to='wagtailimages.image', verbose_name='Banner Background Image'),
        ),
    ]
