# Generated by Django 6.0.3 on 2026-05-16 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_add_banner_bg_image_to_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_headline_2',
            field=models.CharField(default='', max_length=300, verbose_name='Headline 2 Optional'),
        ),
    ]
