# Generated by Django 6.0.3 on 2026-05-16 06:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_hero_headline_2'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nav_phone', models.CharField(default='', max_length=30, verbose_name='Phone Number')),
                ('banner_title', models.CharField(default='About Us', max_length=200)),
                ('banner_description', models.TextField(default='')),
                ('about_subtitle', models.CharField(default='About Us', max_length=100)),
                ('about_heading', models.CharField(default='', max_length=300)),
                ('about_description', models.TextField(default='')),
                ('about_btn_label', models.CharField(default='Read More', max_length=50)),
                ('about_btn_url', models.CharField(default='./about.html', max_length=255)),
                ('choose_subtitle', models.CharField(default='Our Features', max_length=100)),
                ('choose_heading', models.CharField(default='Why You Should Choose Us', max_length=300)),
                ('benefit_subtitle', models.CharField(default='Our Expertise', max_length=100)),
                ('benefit_heading', models.CharField(default='Benefits of Learning With Us', max_length=300)),
                ('benefit_description', models.TextField(default='')),
                ('benefit_video_url', models.URLField(blank=True, verbose_name='Benefit Video URL')),
                ('team_subtitle', models.CharField(default='Instructors', max_length=100)),
                ('team_heading', models.CharField(default='Our Skilled Instructors', max_length=300)),
                ('testimonials_subtitle', models.CharField(default='Reviews', max_length=100)),
                ('testimonials_heading', models.CharField(default="Student's Say About Us", max_length=300)),
                ('footer_newsletter_heading', models.CharField(default='Sign up for the newsletter:', max_length=200)),
                ('footer_about_title', models.CharField(default='About Us', max_length=100)),
                ('footer_about_text', models.TextField(default='')),
                ('footer_links_title', models.CharField(default='Useful Links', max_length=100)),
                ('footer_explore_title', models.CharField(default='Explore', max_length=100)),
                ('footer_contact_title', models.CharField(default='Contact Us', max_length=100)),
                ('footer_contact_phone', models.CharField(default='', max_length=30)),
                ('footer_contact_email', models.EmailField(default='', max_length=254)),
                ('footer_contact_address', models.CharField(default='', max_length=300)),
                ('footer_contact_map_url', models.URLField(blank=True)),
                ('footer_copyright_text', models.CharField(default='', max_length=200)),
                ('about_image1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_page_image1', to='wagtailimages.image', verbose_name='About Image 1 (main)')),
                ('about_image2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_page_image2', to='wagtailimages.image', verbose_name='About Image 2 (overlap)')),
                ('benefit_video_thumb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_benefit_video_thumb', to='wagtailimages.image', verbose_name='Benefit Video Background Image')),
                ('footer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_footer_logo', to='wagtailimages.image')),
                ('nav_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_nav_logo', to='wagtailimages.image', verbose_name='Navbar Logo')),
            ],
            options={
                'verbose_name': 'About Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AboutFooterUsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_footer_useful_links', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutFooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_footer_social_links', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutFooterExploreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_footer_explore_links', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutChooseFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('link_url', models.CharField(blank=True, default='./about.html', max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_choose_icon', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_features', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutBenefitStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('counter', models.CharField(help_text='e.g. "95"', max_length=20)),
                ('suffix', models.CharField(blank=True, help_text='e.g. "%", "+"', max_length=5)),
                ('label', models.CharField(max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_stats', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutPageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=300)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_features', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='home.aboutpage')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_team_photo', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(default='Happy Student', max_length=100)),
                ('quote', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_testimonials', to='home.aboutpage')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_testimonial_photo', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
