# Generated by Django 6.0.3 on 2026-05-19 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_about_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarmenu',
            name='url',
            field=models.CharField(blank=True, default='', help_text='Direct link URL. Leave blank if this item has dropdown sub-items.', max_length=255),
        ),
    ]
