# Generated by Django 6.0.3 on 2026-05-20 07:26

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_navbar_menu_url'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nav_phone', models.CharField(default='', max_length=30)),
                ('nav_login_label', models.CharField(default='Log In', max_length=50)),
                ('nav_login_url', models.CharField(default='#', max_length=255)),
                ('banner_title', models.CharField(default='Start Your Journey With Us', max_length=200)),
                ('banner_description', models.TextField(default='')),
                ('requirements_subtitle', models.CharField(default='Who Can Apply', max_length=100)),
                ('requirements_heading', models.CharField(default='Eligibility & Requirements', max_length=300)),
                ('process_subtitle', models.CharField(default='Simple & Fast', max_length=100)),
                ('process_heading', models.CharField(default='How Our Admissions Works', max_length=300)),
                ('form_subtitle', models.CharField(default='Apply Now', max_length=100)),
                ('form_heading', models.CharField(default='Your Future Starts With One Form', max_length=300)),
                ('form_intro_text', models.TextField(default='')),
                ('form_contact_email', models.EmailField(default='admissions@educiza.com', max_length=254)),
                ('form_submit_label', models.CharField(default='Submit My Application', max_length=100)),
                ('form_success_message', models.TextField(default='Application submitted! Our admissions team will contact you within 48 hours.')),
                ('footer_newsletter_heading', models.CharField(default='Sign up for the newsletter:', max_length=200)),
                ('footer_about_title', models.CharField(default='About Us', max_length=100)),
                ('footer_about_text', models.TextField(default='')),
                ('footer_links_title', models.CharField(default='Useful Links', max_length=100)),
                ('footer_explore_title', models.CharField(default='Programs', max_length=100)),
                ('footer_contact_title', models.CharField(default='Contact Us', max_length=100)),
                ('footer_contact_phone', models.CharField(default='', max_length=30)),
                ('footer_contact_email', models.EmailField(default='', max_length=254)),
                ('footer_contact_address', models.CharField(default='', max_length=300)),
                ('footer_contact_map_url', models.URLField(blank=True)),
                ('footer_copyright_text', models.CharField(default='', max_length=200)),
                ('footer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_footer_logo', to='wagtailimages.image')),
                ('nav_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_nav_logo', to='wagtailimages.image', verbose_name='Navbar Logo')),
            ],
            options={
                'verbose_name': 'Admissions Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AdmissionsFooterUsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_footer_useful_links', to='home.admissionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionsFooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_footer_social_links', to='home.admissionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionsFooterExploreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions_footer_explore_links', to='home.admissionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_class', models.CharField(default='fa-solid fa-check', help_text='Font Awesome class, e.g. "fa-solid fa-graduation-cap"', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_requirements', to='home.admissionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(help_text='Program name shown in the dropdown', max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_programs', to='home.admissionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionIntakeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('bg_choice', models.CharField(choices=[('bg1', 'Green (bg1)'), ('bg2', 'Yellow (bg2)'), ('bg3', 'Red (bg3)')], default='bg1', max_length=10)),
                ('icon_class', models.CharField(default='fa-solid fa-calendar-check', help_text='Font Awesome class, e.g. "fa-solid fa-calendar-check"', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_intake_cards', to='home.admissionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionFormInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_class', models.CharField(default='fa-solid fa-bolt', help_text='Font Awesome class, e.g. "fa-solid fa-bolt"', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_form_infos', to='home.admissionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(help_text='e.g. "98", "5K", "120"', max_length=20)),
                ('suffix', models.CharField(blank=True, help_text='e.g. "%", "+", "K+", "h"', max_length=10)),
                ('label', models.CharField(max_length=150)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_stats', to='home.admissionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('step_number', models.CharField(help_text='e.g. "01", "02"', max_length=5)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_steps', to='home.admissionspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
