# Generated by Django 6.0.3 on 2026-05-20 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_admissions_page'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionspage',
            name='banner_bg_image',
            field=models.ForeignKey(blank=True, help_text='Recommended resolution: 1920 × 486 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_banner_bg', to='wagtailimages.image', verbose_name='Banner Background Image'),
        ),
    ]
