# Generated by Django 6.0.3 on 2026-05-20 15:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_swap_program_for_campus_board'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('nav_phone', models.CharField(default='+92 21 3456 7890', max_length=30)),
                ('nav_login_label', models.CharField(default='Student Portal', max_length=50)),
                ('nav_login_url', models.CharField(default='#', max_length=255)),
                ('banner_title', models.CharField(default='Academics', max_length=200)),
                ('banner_description', models.TextField(default='Shaping minds with a structured curriculum, dedicated faculty, and a culture of academic excellence.')),
                ('curriculum_subtitle', models.CharField(default='Curriculum & Board', max_length=100)),
                ('curriculum_heading', models.CharField(default='A Structured Path to Excellence', max_length=300)),
                ('curriculum_description', models.TextField(default="Our curriculum aligns with Pakistan's leading examination boards, ensuring every student is prepared for national and international standards.")),
                ('grade_ladder_subtitle', models.CharField(default='Grade Structure', max_length=100)),
                ('grade_ladder_heading', models.CharField(default='From First Steps to Board Exams', max_length=200)),
                ('subjects_subtitle', models.CharField(default='Subjects', max_length=100)),
                ('subjects_heading', models.CharField(default='What Your Child Will Learn', max_length=300)),
                ('subjects_description', models.TextField(default="Select a level to explore the subjects taught at each stage of your child's academic journey.")),
                ('calendar_subtitle', models.CharField(default='Academic Year 2024–25', max_length=100)),
                ('calendar_heading', models.CharField(default='Academic Calendar', max_length=300)),
                ('calendar_description', models.TextField(default='Plan ahead with every term, examination period, and holiday mapped out for the full academic year.')),
                ('assessments_subtitle', models.CharField(default='Assessments', max_length=100)),
                ('assessments_heading', models.CharField(default='How We Evaluate Progress', max_length=300)),
                ('assessments_description', models.TextField(default="Our multi-layered assessment system ensures every student's growth is measured fairly, comprehensively, and continuously throughout the year.")),
                ('faculty_subtitle', models.CharField(default='Our Educators', max_length=100)),
                ('faculty_heading', models.CharField(default='Meet the Faculty', max_length=300)),
                ('faculty_description', models.TextField(default='Our qualified and passionate educators bring decades of combined experience to every classroom.')),
                ('achievements_subtitle', models.CharField(default='Results & Achievements', max_length=100)),
                ('achievements_heading', models.CharField(default='A Proven Track Record', max_length=300)),
                ('achievements_description', models.TextField(default='Year after year, our students achieve outstanding results in board examinations and national competitions.')),
                ('downloads_subtitle', models.CharField(default='Resources', max_length=100)),
                ('downloads_heading', models.CharField(default='Downloads & Resources', max_length=300)),
                ('downloads_description', models.TextField(default='Access official documents, syllabi, forms, and schedules — all in one place.')),
                ('cta_heading', models.CharField(default='Ready to Enrol Your Child?', max_length=200)),
                ('cta_text', models.TextField(default="Join hundreds of families who trust Azeem School for a world-class education. Apply today and secure your child's place.")),
                ('cta_button_label', models.CharField(default='Apply for Admission', max_length=100)),
                ('cta_button_url', models.CharField(default='/admissions/', max_length=255)),
                ('footer_newsletter_heading', models.CharField(default='Subscribe to Our Newsletter', max_length=200)),
                ('footer_about_title', models.CharField(default='About Azeem School', max_length=100)),
                ('footer_about_text', models.TextField(default='Providing quality education with modern teaching methods and a nurturing environment for over 25 years in Karachi.')),
                ('footer_links_title', models.CharField(default='Quick Links', max_length=100)),
                ('footer_explore_title', models.CharField(default='Academics', max_length=100)),
                ('footer_contact_title', models.CharField(default='Contact Us', max_length=100)),
                ('footer_contact_phone', models.CharField(default='+92 21 3456 7890', max_length=30)),
                ('footer_contact_email', models.EmailField(default='info@azeem.edu.pk', max_length=254)),
                ('footer_contact_address', models.CharField(default='KDA Scheme, Karachi, Pakistan', max_length=300)),
                ('footer_contact_map_url', models.URLField(blank=True)),
                ('footer_copyright_text', models.CharField(default='© 2025 Azeem School. All Rights Reserved.', max_length=200)),
                ('banner_bg_image', models.ForeignKey(blank=True, help_text='Recommended resolution: 1920 × 486 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_banner_bg', to='wagtailimages.image', verbose_name='Banner Background Image')),
                ('footer_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_footer_logo', to='wagtailimages.image')),
                ('nav_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_nav_logo', to='wagtailimages.image', verbose_name='Navbar Logo')),
            ],
            options={
                'verbose_name': 'Academics Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='AcademicsFooterUsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics_footer_useful_links', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicsFooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('instagram', 'Instagram'), ('linkedin', 'LinkedIn')], max_length=20)),
                ('url', models.URLField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics_footer_social_links', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicsFooterExploreLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academics_footer_explore_links', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicGradeLadderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_choice', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book', 'Book (closed)'), ('fa-solid fa-book-open', 'Book (open)'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Calculator / Maths'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-microscope', 'Microscope / Science'), ('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-bolt', 'Bolt / Electricity'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-language', 'Language / English'), ('fa-solid fa-pen-nib', 'Pen / Urdu Writing'), ('fa-solid fa-pen-to-square', 'Edit / Exam'), ('fa-solid fa-palette', 'Art & Craft'), ('fa-solid fa-map', 'Map / Social Studies'), ('fa-solid fa-flag', 'Flag / Pakistan Studies'), ('fa-solid fa-moon', 'Moon / Islamic Studies'), ('fa-solid fa-seedling', 'Seedling / Early Years'), ('fa-solid fa-person-running', 'Physical Education'), ('fa-solid fa-heart', 'Heart / Moral Education'), ('fa-solid fa-earth-asia', 'Globe / General Knowledge'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-clipboard-check', 'Clipboard Check'), ('fa-solid fa-file-pen', 'File Pen / Test'), ('fa-solid fa-file-invoice', 'File / Document'), ('fa-solid fa-list-check', 'List / Book List'), ('fa-solid fa-file-arrow-down', 'File Download'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-leaf', 'Leaf / Autumn Term'), ('fa-solid fa-snowflake', 'Snowflake / Winter'), ('fa-solid fa-sun', 'Sun / Summer'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea'), ('fa-solid fa-users', 'Users / Group'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building')], default='fa-solid fa-book-open', max_length=100)),
                ('icon_color', models.CharField(choices=[('gl-accent', 'Lime / Accent'), ('gl-blue', 'Blue / Purple'), ('gl-green', 'Green'), ('gl-yellow', 'Yellow'), ('gl-pink', 'Pink'), ('gl-purple', 'Violet'), ('gl-cyan', 'Cyan')], default='gl-blue', help_text='Icon colour on dark-navy background', max_length=20)),
                ('title', models.CharField(default='Grade Level', max_length=100)),
                ('subtitle', models.CharField(default='', help_text='e.g. "Class 1 – Class 5"', max_length=200)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_ladder_items', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(default='Faculty Name', max_length=100)),
                ('subject', models.CharField(default='Subject', max_length=100)),
                ('experience', models.CharField(blank=True, default='', help_text='e.g. "10 yrs experience"', max_length=50)),
                ('avatar_initial', models.CharField(default='A', help_text='1–2 letters displayed in the avatar circle', max_length=2)),
                ('avatar_color', models.CharField(choices=[('#6a52e0', 'Purple'), ('#52b788', 'Green'), ('#f4b942', 'Yellow / Amber'), ('#ec407a', 'Pink'), ('#ab47bc', 'Violet'), ('#26c6da', 'Cyan'), ('#42a5f5', 'Blue'), ('#ff7043', 'Orange'), ('#1f1741', 'Dark Navy')], default='#6a52e0', help_text='Avatar circle background colour', max_length=20)),
                ('is_hod', models.BooleanField(default=False, verbose_name='Head of Department (HOD)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_faculty', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_choice', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book', 'Book (closed)'), ('fa-solid fa-book-open', 'Book (open)'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Calculator / Maths'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-microscope', 'Microscope / Science'), ('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-bolt', 'Bolt / Electricity'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-language', 'Language / English'), ('fa-solid fa-pen-nib', 'Pen / Urdu Writing'), ('fa-solid fa-pen-to-square', 'Edit / Exam'), ('fa-solid fa-palette', 'Art & Craft'), ('fa-solid fa-map', 'Map / Social Studies'), ('fa-solid fa-flag', 'Flag / Pakistan Studies'), ('fa-solid fa-moon', 'Moon / Islamic Studies'), ('fa-solid fa-seedling', 'Seedling / Early Years'), ('fa-solid fa-person-running', 'Physical Education'), ('fa-solid fa-heart', 'Heart / Moral Education'), ('fa-solid fa-earth-asia', 'Globe / General Knowledge'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-clipboard-check', 'Clipboard Check'), ('fa-solid fa-file-pen', 'File Pen / Test'), ('fa-solid fa-file-invoice', 'File / Document'), ('fa-solid fa-list-check', 'List / Book List'), ('fa-solid fa-file-arrow-down', 'File Download'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-leaf', 'Leaf / Autumn Term'), ('fa-solid fa-snowflake', 'Snowflake / Winter'), ('fa-solid fa-sun', 'Sun / Summer'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea'), ('fa-solid fa-users', 'Users / Group'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building')], default='fa-solid fa-file-arrow-down', max_length=100)),
                ('icon_color', models.CharField(choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-yellow', 'Yellow / Amber'), ('icon-pink', 'Pink / Red'), ('icon-purple', 'Purple'), ('icon-cyan', 'Cyan / Teal'), ('icon-orange', 'Orange'), ('icon-dark', 'Dark Navy + Accent')], default='icon-blue', max_length=20)),
                ('title', models.CharField(default='Document Title', max_length=200)),
                ('description', models.CharField(default='PDF · 1 MB', help_text='e.g. "Complete syllabus for all classes · PDF · 1.2 MB"', max_length=200)),
                ('url', models.CharField(default='#', help_text='URL to the file. Use "#" as placeholder if not available yet.', max_length=500)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_downloads', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicCalendarTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('badge_label', models.CharField(default='Term 1', help_text='Lime badge label, e.g. "Term 1", "Break", "Finals"', max_length=50)),
                ('badge_icon_choice', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book', 'Book (closed)'), ('fa-solid fa-book-open', 'Book (open)'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Calculator / Maths'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-microscope', 'Microscope / Science'), ('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-bolt', 'Bolt / Electricity'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-language', 'Language / English'), ('fa-solid fa-pen-nib', 'Pen / Urdu Writing'), ('fa-solid fa-pen-to-square', 'Edit / Exam'), ('fa-solid fa-palette', 'Art & Craft'), ('fa-solid fa-map', 'Map / Social Studies'), ('fa-solid fa-flag', 'Flag / Pakistan Studies'), ('fa-solid fa-moon', 'Moon / Islamic Studies'), ('fa-solid fa-seedling', 'Seedling / Early Years'), ('fa-solid fa-person-running', 'Physical Education'), ('fa-solid fa-heart', 'Heart / Moral Education'), ('fa-solid fa-earth-asia', 'Globe / General Knowledge'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-clipboard-check', 'Clipboard Check'), ('fa-solid fa-file-pen', 'File Pen / Test'), ('fa-solid fa-file-invoice', 'File / Document'), ('fa-solid fa-list-check', 'List / Book List'), ('fa-solid fa-file-arrow-down', 'File Download'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-leaf', 'Leaf / Autumn Term'), ('fa-solid fa-snowflake', 'Snowflake / Winter'), ('fa-solid fa-sun', 'Sun / Summer'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea'), ('fa-solid fa-users', 'Users / Group'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building')], default='fa-solid fa-leaf', max_length=100)),
                ('title', models.CharField(default='Autumn Term', max_length=100)),
                ('date_range', models.CharField(default='Sep 2 – Nov 15', max_length=100)),
                ('events', models.TextField(default='', help_text='One event per line, e.g.:\nSchool reopens — Sep 2\nUnit Test 1 — Oct 4')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_terms', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('border_color', models.CharField(choices=[('soft-blue', 'Soft Blue (primary)'), ('accent', 'Lime / Accent (highlight)')], default='soft-blue', help_text='Left border colour of this board card', max_length=20)),
                ('icon_bg_dark', models.BooleanField(default=False, help_text='Tick for dark-navy icon background instead of soft-blue')),
                ('icon_choice', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book', 'Book (closed)'), ('fa-solid fa-book-open', 'Book (open)'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Calculator / Maths'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-microscope', 'Microscope / Science'), ('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-bolt', 'Bolt / Electricity'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-language', 'Language / English'), ('fa-solid fa-pen-nib', 'Pen / Urdu Writing'), ('fa-solid fa-pen-to-square', 'Edit / Exam'), ('fa-solid fa-palette', 'Art & Craft'), ('fa-solid fa-map', 'Map / Social Studies'), ('fa-solid fa-flag', 'Flag / Pakistan Studies'), ('fa-solid fa-moon', 'Moon / Islamic Studies'), ('fa-solid fa-seedling', 'Seedling / Early Years'), ('fa-solid fa-person-running', 'Physical Education'), ('fa-solid fa-heart', 'Heart / Moral Education'), ('fa-solid fa-earth-asia', 'Globe / General Knowledge'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-clipboard-check', 'Clipboard Check'), ('fa-solid fa-file-pen', 'File Pen / Test'), ('fa-solid fa-file-invoice', 'File / Document'), ('fa-solid fa-list-check', 'List / Book List'), ('fa-solid fa-file-arrow-down', 'File Download'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-leaf', 'Leaf / Autumn Term'), ('fa-solid fa-snowflake', 'Snowflake / Winter'), ('fa-solid fa-sun', 'Sun / Summer'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea'), ('fa-solid fa-users', 'Users / Group'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building')], default='fa-solid fa-graduation-cap', max_length=100)),
                ('name', models.CharField(default='Board Name', max_length=200)),
                ('description', models.TextField(default='')),
                ('tag_1', models.CharField(blank=True, default='', help_text='Grade / group tag (optional)', max_length=100)),
                ('tag_2', models.CharField(blank=True, default='', help_text='Grade / group tag (optional)', max_length=100)),
                ('tag_3', models.CharField(blank=True, default='', help_text='Grade / group tag (optional)', max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_boards', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_choice', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book', 'Book (closed)'), ('fa-solid fa-book-open', 'Book (open)'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Calculator / Maths'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-microscope', 'Microscope / Science'), ('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-bolt', 'Bolt / Electricity'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-language', 'Language / English'), ('fa-solid fa-pen-nib', 'Pen / Urdu Writing'), ('fa-solid fa-pen-to-square', 'Edit / Exam'), ('fa-solid fa-palette', 'Art & Craft'), ('fa-solid fa-map', 'Map / Social Studies'), ('fa-solid fa-flag', 'Flag / Pakistan Studies'), ('fa-solid fa-moon', 'Moon / Islamic Studies'), ('fa-solid fa-seedling', 'Seedling / Early Years'), ('fa-solid fa-person-running', 'Physical Education'), ('fa-solid fa-heart', 'Heart / Moral Education'), ('fa-solid fa-earth-asia', 'Globe / General Knowledge'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-clipboard-check', 'Clipboard Check'), ('fa-solid fa-file-pen', 'File Pen / Test'), ('fa-solid fa-file-invoice', 'File / Document'), ('fa-solid fa-list-check', 'List / Book List'), ('fa-solid fa-file-arrow-down', 'File Download'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-leaf', 'Leaf / Autumn Term'), ('fa-solid fa-snowflake', 'Snowflake / Winter'), ('fa-solid fa-sun', 'Sun / Summer'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea'), ('fa-solid fa-users', 'Users / Group'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building')], default='fa-solid fa-clipboard-check', max_length=100)),
                ('icon_color', models.CharField(choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-yellow', 'Yellow / Amber'), ('icon-pink', 'Pink / Red'), ('icon-purple', 'Purple'), ('icon-cyan', 'Cyan / Teal'), ('icon-orange', 'Orange'), ('icon-dark', 'Dark Navy + Accent')], default='icon-blue', max_length=20)),
                ('title', models.CharField(default='Assessment Type', max_length=200)),
                ('description', models.TextField(default='')),
                ('weight', models.CharField(default='20%', help_text='Weightage badge text, e.g. "20% Weightage"', max_length=20)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_assessments', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicAchievementStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(default='98', max_length=20)),
                ('suffix', models.CharField(blank=True, default='%', help_text='e.g. "%", "+", "×"', max_length=10)),
                ('label', models.CharField(default='Overall Pass Rate', max_length=150)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_stats', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicAchievementCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_choice', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book', 'Book (closed)'), ('fa-solid fa-book-open', 'Book (open)'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Calculator / Maths'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-microscope', 'Microscope / Science'), ('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-bolt', 'Bolt / Electricity'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-language', 'Language / English'), ('fa-solid fa-pen-nib', 'Pen / Urdu Writing'), ('fa-solid fa-pen-to-square', 'Edit / Exam'), ('fa-solid fa-palette', 'Art & Craft'), ('fa-solid fa-map', 'Map / Social Studies'), ('fa-solid fa-flag', 'Flag / Pakistan Studies'), ('fa-solid fa-moon', 'Moon / Islamic Studies'), ('fa-solid fa-seedling', 'Seedling / Early Years'), ('fa-solid fa-person-running', 'Physical Education'), ('fa-solid fa-heart', 'Heart / Moral Education'), ('fa-solid fa-earth-asia', 'Globe / General Knowledge'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-clipboard-check', 'Clipboard Check'), ('fa-solid fa-file-pen', 'File Pen / Test'), ('fa-solid fa-file-invoice', 'File / Document'), ('fa-solid fa-list-check', 'List / Book List'), ('fa-solid fa-file-arrow-down', 'File Download'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-leaf', 'Leaf / Autumn Term'), ('fa-solid fa-snowflake', 'Snowflake / Winter'), ('fa-solid fa-sun', 'Sun / Summer'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea'), ('fa-solid fa-users', 'Users / Group'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building')], default='fa-solid fa-trophy', max_length=100)),
                ('title', models.CharField(default='Achievement Highlight', max_length=200)),
                ('description', models.TextField(default='')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_cards', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(default='14', help_text='e.g. "14", "98", "25"', max_length=20)),
                ('suffix', models.CharField(blank=True, default='+', help_text='e.g. "+", "%", "×"', max_length=10)),
                ('label', models.CharField(default='Subjects Offered', max_length=150)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_stats', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AcademicSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('level', models.CharField(choices=[('early_years', 'Early Years (Pre-Mon, Mon, KG1, KG2)'), ('primary', 'Primary (Class 1–5)'), ('middle', 'Middle (Class 6–8)'), ('secondary', 'Secondary (Class 9–10)')], default='primary', max_length=20)),
                ('name', models.CharField(default='Subject', max_length=100)),
                ('icon_choice', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book', 'Book (closed)'), ('fa-solid fa-book-open', 'Book (open)'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Calculator / Maths'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-microscope', 'Microscope / Science'), ('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-bolt', 'Bolt / Electricity'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-language', 'Language / English'), ('fa-solid fa-pen-nib', 'Pen / Urdu Writing'), ('fa-solid fa-pen-to-square', 'Edit / Exam'), ('fa-solid fa-palette', 'Art & Craft'), ('fa-solid fa-map', 'Map / Social Studies'), ('fa-solid fa-flag', 'Flag / Pakistan Studies'), ('fa-solid fa-moon', 'Moon / Islamic Studies'), ('fa-solid fa-seedling', 'Seedling / Early Years'), ('fa-solid fa-person-running', 'Physical Education'), ('fa-solid fa-heart', 'Heart / Moral Education'), ('fa-solid fa-earth-asia', 'Globe / General Knowledge'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-clipboard-check', 'Clipboard Check'), ('fa-solid fa-file-pen', 'File Pen / Test'), ('fa-solid fa-file-invoice', 'File / Document'), ('fa-solid fa-list-check', 'List / Book List'), ('fa-solid fa-file-arrow-down', 'File Download'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-leaf', 'Leaf / Autumn Term'), ('fa-solid fa-snowflake', 'Snowflake / Winter'), ('fa-solid fa-sun', 'Sun / Summer'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea'), ('fa-solid fa-users', 'Users / Group'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building')], default='fa-solid fa-book', max_length=100)),
                ('icon_color', models.CharField(choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-yellow', 'Yellow / Amber'), ('icon-pink', 'Pink / Red'), ('icon-purple', 'Purple'), ('icon-cyan', 'Cyan / Teal'), ('icon-orange', 'Orange'), ('icon-dark', 'Dark Navy + Accent')], default='icon-blue', max_length=20)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_subjects', to='home.academicspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
