# Generated by Django 6.0.3 on 2026-05-20 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_academics_page'),
        ('wagtaildocs', '0014_alter_document_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicdownload',
            name='url',
        ),
        migrations.AddField(
            model_name='academicdownload',
            name='document',
            field=models.ForeignKey(blank=True, help_text='Upload a PDF or any file. Visitors will download it on click.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document'),
        ),
    ]
