# Generated by Django 6.0.3 on 2026-05-20 19:46

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_custom_document_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdownload',
            name='document',
            field=models.FileField(blank=True, help_text='Upload a PDF or any file. Visitors will download it on click.', null=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='documents', verbose_name='File'),
        ),
    ]
