# Generated by Django 6.0.3 on 2026-05-23 18:31

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_facilitiespage_facilitiesfooterusefullink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityartscard',
            name='icon_color',
            field=models.CharField(choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-teal', 'Teal'), ('icon-purple', 'Purple'), ('icon-orange', 'Orange'), ('icon-yellow', 'Yellow'), ('icon-pink', 'Pink'), ('icon-cyan', 'Cyan')], default='icon-pink', help_text='Icon background colour theme', max_length=20),
        ),
        migrations.AddField(
            model_name='facilitylab',
            name='icon_color',
            field=models.CharField(choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-teal', 'Teal'), ('icon-purple', 'Purple'), ('icon-orange', 'Orange'), ('icon-yellow', 'Yellow'), ('icon-pink', 'Pink'), ('icon-cyan', 'Cyan')], default='icon-blue', help_text='Icon background colour theme', max_length=20),
        ),
        migrations.AddField(
            model_name='facilitysport',
            name='icon_choice',
            field=models.CharField(choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-futbol', help_text='Icon shown at the top of the sport card', max_length=100),
        ),
        migrations.CreateModel(
            name='FacilityOverviewTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_choice', models.CharField(choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-school', help_text='Font Awesome icon class', max_length=100)),
                ('icon_color', models.CharField(choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-teal', 'Teal'), ('icon-purple', 'Purple'), ('icon-orange', 'Orange'), ('icon-yellow', 'Yellow'), ('icon-pink', 'Pink'), ('icon-cyan', 'Cyan')], default='icon-blue', help_text='Icon background colour theme', max_length=20)),
                ('title', models.CharField(default='Facility Name', max_length=100)),
                ('description', models.CharField(default='Short description of this facility area.', max_length=250)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_tiles', to='home.facilitiespage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
