# Generated by Django 6.0.3 on 2026-05-28 18:34

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_facilityartscard_icon_color_facilitylab_icon_color_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(default='News & Gallery', max_length=200)),
                ('banner_description', models.TextField(default='Stay updated with the latest happenings, achievements, and moments from across Azeem School.')),
                ('ticker_items', models.TextField(default='Admissions Open for 2025–26 Academic Year — Apply Before July 31st!\nAnnual Sports Day — Friday, 6th June 2025 at Main Ground\nGrade 10 & 12 Board Exams Begin — 12th May 2025. Best of luck to all students!\nScience Fair 2025 — Project Submissions Close 20th May. Register Now.\nParent-Teacher Meeting — Saturday 24th May, 9 AM to 1 PM', help_text='One announcement per line. These scroll in the lime ticker bar at the top of the page.')),
                ('news_eyebrow', models.CharField(default="Editor's Pick", max_length=100)),
                ('news_heading', models.CharField(default='Latest from Azeem School', max_length=200)),
                ('ann_eyebrow', models.CharField(default='Notice Board', max_length=100)),
                ('ann_heading', models.CharField(default='Announcements & Upcoming Events', max_length=200)),
                ('events_panel_heading', models.CharField(default='Upcoming Events', max_length=100)),
                ('gallery_eyebrow', models.CharField(default='Campus Moments', max_length=100)),
                ('gallery_heading', models.CharField(default='School Gallery', max_length=200)),
                ('gallery_description', models.TextField(default='A visual celebration of life at Azeem School — from classrooms to cricket grounds and everything in between.')),
                ('cta_heading', models.CharField(default='Never Miss an Update', max_length=200)),
                ('cta_text', models.TextField(default='Subscribe to the Azeem School newsletter and get announcements, event reminders, and highlights delivered straight to your inbox.')),
            ],
            options={
                'verbose_name': 'News & Gallery Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsGalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('events', 'Events'), ('sports', 'Sports'), ('arts', 'Arts'), ('campus', 'Campus'), ('academics', 'Academics')], default='events', max_length=20)),
                ('title', models.CharField(help_text='Shown in the hover overlay', max_length=200)),
                ('alt_text', models.CharField(blank=True, default='', help_text='Accessibility alt text (leave blank to use title)', max_length=200)),
                ('image', models.ForeignKey(blank=True, help_text='Gallery photo (any aspect ratio — CSS handles the masonry layout)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_gallery_photo_image', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_gallery_photos', to='home.newspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark ONE article as Featured — it shows as the large hero card at the top.')),
                ('category', models.CharField(choices=[('event', 'Event'), ('academic', 'Academic'), ('sports', 'Sports'), ('arts', 'Arts'), ('notice', 'Notice'), ('science', 'Science')], default='event', max_length=20)),
                ('date', models.DateField(help_text='Publication date shown on the card and in the popup')),
                ('title', models.CharField(max_length=300)),
                ('excerpt', models.TextField(help_text='Short summary shown on the card (2-3 sentences). Keep it punchy.')),
                ('body', models.TextField(help_text='Full article body shown inside the popup modal.\nUse blank lines to separate paragraphs.')),
                ('is_apply_now', models.BooleanField(default=False, help_text='If ticked, the card shows an "Apply Now" button linking to /admissions/ instead of "Read More".', verbose_name='Show "Apply Now" button')),
                ('image', models.ForeignKey(blank=True, help_text='Article cover photo (recommended: 900 × 600 px)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_article_image', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_articles', to='home.newspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('ann_type', models.CharField(choices=[('academic', 'Academic'), ('event', 'Event'), ('sports', 'Sports'), ('exam', 'Exam'), ('notice', 'Notice')], default='notice', max_length=20)),
                ('icon_choice', models.CharField(choices=[('fa-solid fa-bell', 'Bell'), ('fa-solid fa-thumbtack', 'Pin / Thumbtack'), ('fa-solid fa-file-pen', 'File / Exam'), ('fa-solid fa-door-open', 'Admissions / Door'), ('fa-solid fa-trophy', 'Trophy / Achievement'), ('fa-solid fa-chalkboard-user', 'Parent-Teacher Meeting'), ('fa-solid fa-flask', 'Science / Lab'), ('fa-solid fa-futbol', 'Sports / Football'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-calendar-days', 'Calendar / Schedule'), ('fa-solid fa-graduation-cap', 'Graduation / Results'), ('fa-solid fa-star', 'Achievement / Star'), ('fa-solid fa-bullhorn', 'Notice / Announcement'), ('fa-solid fa-book-open', 'Academics / Books'), ('fa-solid fa-music', 'Arts / Music'), ('fa-solid fa-heart-pulse', 'Health / Medical'), ('fa-solid fa-shield-halved', 'Safety / Security'), ('fa-solid fa-utensils', 'Cafeteria'), ('fa-solid fa-mosque', 'Prayer / Event'), ('fa-solid fa-award', 'Award / Recognition')], default='fa-solid fa-bell', max_length=100)),
                ('icon_style', models.CharField(choices=[('ai-purple', 'Purple'), ('ai-lime', 'Lime / Accent'), ('ai-blue', 'Blue'), ('ai-pink', 'Pink'), ('ai-orange', 'Orange'), ('ai-teal', 'Teal')], default='ai-purple', help_text='Background colour of the icon box', max_length=20)),
                ('badge_style', models.CharField(choices=[('ab-event', 'Event (purple)'), ('ab-academic', 'Academic (blue)'), ('ab-sports', 'Sports (lime)'), ('ab-exam', 'Exam (orange)'), ('ab-notice', 'Notice (pink)')], default='ab-notice', help_text='Colour of the category badge pill', max_length=20)),
                ('date_label', models.CharField(help_text='Right-side date label, e.g. "May 12, 2025" or "Open till Jul 31"', max_length=60)),
                ('is_pinned', models.BooleanField(default=False, help_text='Show a thumbtack pin icon for important / top announcements')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(help_text='Short description shown below the title')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_announcements', to='home.newspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsUpcomingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('day', models.CharField(help_text='Day number shown in the date box, e.g. "12"', max_length=5)),
                ('month', models.CharField(help_text='Month abbreviation, e.g. "May" or "Jun"', max_length=10)),
                ('badge_type', models.CharField(choices=[('upcoming', 'Upcoming'), ('today', 'Today / This Month')], default='upcoming', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('time', models.CharField(help_text='e.g. "8:00 AM" or "9:00 AM – 1 PM"', max_length=60)),
                ('location', models.CharField(help_text='e.g. "Main Hall" or "Sports Ground"', max_length=120)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_upcoming_events', to='home.newspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
