# Generated by Django 6.0.3 on 2026-05-28 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_newspage_newsgalleryphoto_newsarticle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(choices=[('flagship', 'Flagship Event of the Year'), ('annual_day', 'Annual Day & Prize Distribution'), ('sports_day', 'Sports Day'), ('science_fair', 'Science Fair & Exhibition'), ('cultural', 'Cultural Festival'), ('graduation', 'Graduation Ceremony'), ('trip', 'Educational Trip & Excursion'), ('result', 'Board Results & Achievements'), ('exam_notice', 'Exam Schedule & Notice'), ('academic', 'Academic Update'), ('award', 'Award & Recognition'), ('olympiad', 'Olympiad & Competition'), ('cambridge', 'Cambridge / O-A Level'), ('sports', 'Sports & Athletics'), ('inter_school', 'Inter-School Tournament'), ('arts', 'Arts, Music & Drama'), ('debate', 'Debate & Public Speaking'), ('admissions', 'Admissions Open'), ('notice', 'Important Notice'), ('welfare', 'Student Welfare & Health'), ('community', 'Community & Social Work'), ('pakistan_day', 'Pakistan Day / National Event'), ('ramadan', 'Ramadan & Islamic Events'), ('staff', 'Staff & Faculty News')], default='event', max_length=20),
        ),
    ]
