# Generated by Django 6.0.3 on 2026-06-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_remove_trustcard_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='admissions_cta_btn_label',
            field=models.CharField(blank=True, default='Apply Now', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='admissions_cta_btn_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='admissions_cta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='admissions_cta_subtitle',
            field=models.CharField(blank=True, default='Admissions Open', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='admissions_cta_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
