# Generated by Django 6.0.3 on 2026-06-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_homepage_admissions_cta_btn_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='nav_school_name',
            field=models.CharField(blank=True, default='', help_text="Short name shown next to the logo, e.g. 'Azeem School'", max_length=100, verbose_name='School Short Name'),
        ),
    ]
