# Generated by Django 6.0.3 on 2026-06-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_homepage_nav_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='boards_description',
            field=models.TextField(default='We follow the curriculum of top educational boards to ensure quality education for our students.'),
        ),
        migrations.AlterField(
            model_name='boardcard',
            name='board_name',
            field=models.CharField(help_text='Full name shown as the card title.  e.g.  BSEK  (Matric — Class 9 & 10)', max_length=200, verbose_name='Board / Programme Name'),
        ),
        migrations.AlterField(
            model_name='boardcard',
            name='description',
            field=models.TextField(help_text="2–3 sentences about this board/programme.  e.g.  Nationally recognised Matric qualification aligned with Pakistan's federal curriculum, preparing students for competitive examinations across the country.", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='boardcard',
            name='icon_class',
            field=models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-users', 'Group / Students'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-microscope', 'Science Lab'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-shield-halved', 'Excellence / Discipline'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-award', 'Award / Recognition'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry'), ('fa-solid fa-atom', 'Physics'), ('fa-solid fa-dna', 'Biology'), ('fa-solid fa-language', 'Languages'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-earth-asia', 'General Knowledge'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-door-open', 'Admissions'), ('fa-solid fa-file-pen', 'Exams / Tests')], default='fa-solid fa-graduation-cap', help_text='Icon shown in the coloured header. Choose from the dropdown — no image upload needed.', max_length=100, verbose_name='Card Icon'),
        ),
        migrations.AlterField(
            model_name='boardcard',
            name='learn_more_url',
            field=models.CharField(blank=True, help_text='URL the Explore Program button links to.  e.g.  /academics/', max_length=255, verbose_name="'Explore Program' Button URL"),
        ),
        migrations.AlterField(
            model_name='boardcard',
            name='level_label',
            field=models.CharField(blank=True, help_text='Shown as a small label below the board name.  e.g.  Class 9 – 10   or   O Level & A Level', max_length=100, verbose_name='Level / Class Range'),
        ),
        migrations.AlterField(
            model_name='boardcard',
            name='subjects_list',
            field=models.CharField(blank=True, help_text='Type subjects separated by commas — they appear as tags on the card.  e.g.  Physics, Chemistry, Biology, Mathematics, Urdu, Islamiyat', max_length=400, verbose_name='Subjects (comma-separated)'),
        ),
        migrations.AlterField(
            model_name='boardcard',
            name='tab',
            field=models.CharField(choices=[('all', 'All'), ('matric', 'Matric'), ('intermediate', 'Intermediate'), ('cambridge', 'Cambridge'), ('primary', 'Primary')], default='all', help_text='Which board category this card belongs to. e.g. Matric, Intermediate, Cambridge, Primary.', max_length=20, verbose_name='Category Tab'),
        ),
    ]
