# Generated by Django 6.0.3 on 2026-06-06 20:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_homepage_boards_description_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='facilities_description',
            field=models.TextField(blank=True, default='Every resource a student needs — under one roof, in a safe and inspiring environment.', help_text='One or two sentences shown below the heading.', verbose_name='Section Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facilities_subtitle',
            field=models.CharField(blank=True, default='Campus Life', help_text='Small label above the heading.  e.g.  Campus Life', max_length=100, verbose_name='Section Label'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='facilities_title',
            field=models.CharField(blank=True, default='World-Class Facilities', help_text='Main heading.  e.g.  World-Class Facilities', max_length=300, verbose_name='Section Heading'),
        ),
        migrations.CreateModel(
            name='HomeFacilityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_class', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-users', 'Group / Students'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-microscope', 'Science Lab'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-shield-halved', 'Excellence / Discipline'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-award', 'Award / Recognition'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry'), ('fa-solid fa-atom', 'Physics'), ('fa-solid fa-dna', 'Biology'), ('fa-solid fa-language', 'Languages'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-earth-asia', 'General Knowledge'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-door-open', 'Admissions'), ('fa-solid fa-file-pen', 'Exams / Tests')], default='fa-solid fa-school', help_text='Icon shown on the card.  e.g.  Computer / IT  for a computer lab.', max_length=100, verbose_name='Card Icon')),
                ('icon_bg_color', models.CharField(blank=True, default='', help_text='Leave blank for gold (default).  Or enter a CSS colour code to customise.  e.g.  #16a34a  (green)   #ca8a04  (amber)   #ec407a  (pink)', max_length=30, verbose_name='Icon Colour (optional)')),
                ('title', models.CharField(help_text='e.g.  Computer Labs', max_length=200, verbose_name='Facility Name')),
                ('description', models.CharField(help_text='One sentence.  e.g.  Modern PCs, high-speed internet and coding tools for all grades.', max_length=300, verbose_name='Short Description')),
                ('link_url', models.CharField(blank=True, default='/facilities/', help_text='Where the card links to.  Default:  /facilities/', max_length=255, verbose_name='Card Link URL')),
                ('image', models.ForeignKey(blank=True, help_text='Photo shown as the card background. Use a clear, high-quality image of this facility.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_teaser_image', to='wagtailimages.image', verbose_name='Background Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_teasers', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
