# Generated by Django 6.0.3 on 2026-06-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_homepage_facilities_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='show_explore_pages',
            field=models.BooleanField(default=True, help_text='Tick to display the 6 page-navigation cards (About, Academics, Admissions, Facilities, News, Contact). Untick to hide the section.', verbose_name="Show 'Explore Azeem School' section"),
        ),
    ]
