# Generated by Django 6.0.3 on 2026-06-07 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_homepage_show_explore_pages'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homefacilitycard',
            name='icon_bg_color',
            field=models.CharField(blank=True, choices=[('', 'Gold (default)'), ('#1565c0', 'Blue'), ('#16a34a', 'Green'), ('#ca8a04', 'Amber / Yellow'), ('#ec407a', 'Pink / Red'), ('#ab47bc', 'Purple'), ('#0097a7', 'Teal / Cyan'), ('#e65100', 'Orange'), ('#1f1741', 'Dark Navy')], default='', max_length=30, verbose_name='Icon Background Colour'),
        ),
        migrations.AlterField(
            model_name='homefacilitycard',
            name='icon_class',
            field=models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-users', 'Group / Students'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-microscope', 'Science Lab'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-shield-halved', 'Excellence / Discipline'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-award', 'Award / Recognition'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry'), ('fa-solid fa-atom', 'Physics'), ('fa-solid fa-dna', 'Biology'), ('fa-solid fa-language', 'Languages'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-earth-asia', 'General Knowledge'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-door-open', 'Admissions'), ('fa-solid fa-file-pen', 'Exams / Tests')], default='fa-solid fa-school', max_length=100, verbose_name='Card Icon'),
        ),
        migrations.AlterField(
            model_name='homefacilitycard',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Photo shown as the card background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_teaser_image', to='wagtailimages.image', verbose_name='Background Image'),
        ),
        migrations.AlterField(
            model_name='homefacilitycard',
            name='link_url',
            field=models.CharField(blank=True, default='/facilities/', help_text='Default:  /facilities/', max_length=255, verbose_name='Card Link URL'),
        ),
    ]
