# Generated by Django 6.0.3 on 2026-06-07 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_homefacilitycard_icon_bg_color_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='fac1_color',
            field=models.CharField(blank=True, choices=[('', 'Gold (default)'), ('#1565c0', 'Blue'), ('#16a34a', 'Green'), ('#ca8a04', 'Amber / Yellow'), ('#ec407a', 'Pink / Red'), ('#ab47bc', 'Purple'), ('#0097a7', 'Teal / Cyan'), ('#e65100', 'Orange'), ('#1f1741', 'Dark Navy')], default='', max_length=30, verbose_name='Card 1 — Icon Colour'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac1_desc',
            field=models.CharField(blank=True, default='Modern PCs, high-speed internet and coding tools for all grades.', max_length=300, verbose_name='Card 1 — Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac1_icon',
            field=models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-users', 'Group / Students'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-microscope', 'Science Lab'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-shield-halved', 'Excellence / Discipline'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-award', 'Award / Recognition'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry'), ('fa-solid fa-atom', 'Physics'), ('fa-solid fa-dna', 'Biology'), ('fa-solid fa-language', 'Languages'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-earth-asia', 'General Knowledge'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-door-open', 'Admissions'), ('fa-solid fa-file-pen', 'Exams / Tests')], default='fa-solid fa-computer', max_length=100, verbose_name='Card 1 — Icon'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac1_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Card 1 — Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac1_title',
            field=models.CharField(blank=True, default='Computer Labs', max_length=200, verbose_name='Card 1 — Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac1_url',
            field=models.CharField(blank=True, default='/facilities/', max_length=255, verbose_name='Card 1 — Link URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac2_color',
            field=models.CharField(blank=True, choices=[('', 'Gold (default)'), ('#1565c0', 'Blue'), ('#16a34a', 'Green'), ('#ca8a04', 'Amber / Yellow'), ('#ec407a', 'Pink / Red'), ('#ab47bc', 'Purple'), ('#0097a7', 'Teal / Cyan'), ('#e65100', 'Orange'), ('#1f1741', 'Dark Navy')], default='#16a34a', max_length=30, verbose_name='Card 2 — Icon Colour'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac2_desc',
            field=models.CharField(blank=True, default='Fully equipped Physics, Chemistry, and Biology laboratories.', max_length=300, verbose_name='Card 2 — Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac2_icon',
            field=models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-users', 'Group / Students'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-microscope', 'Science Lab'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-shield-halved', 'Excellence / Discipline'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-award', 'Award / Recognition'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry'), ('fa-solid fa-atom', 'Physics'), ('fa-solid fa-dna', 'Biology'), ('fa-solid fa-language', 'Languages'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-earth-asia', 'General Knowledge'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-door-open', 'Admissions'), ('fa-solid fa-file-pen', 'Exams / Tests')], default='fa-solid fa-microscope', max_length=100, verbose_name='Card 2 — Icon'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac2_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Card 2 — Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac2_title',
            field=models.CharField(blank=True, default='Science Labs', max_length=200, verbose_name='Card 2 — Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac2_url',
            field=models.CharField(blank=True, default='/facilities/', max_length=255, verbose_name='Card 2 — Link URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac3_color',
            field=models.CharField(blank=True, choices=[('', 'Gold (default)'), ('#1565c0', 'Blue'), ('#16a34a', 'Green'), ('#ca8a04', 'Amber / Yellow'), ('#ec407a', 'Pink / Red'), ('#ab47bc', 'Purple'), ('#0097a7', 'Teal / Cyan'), ('#e65100', 'Orange'), ('#1f1741', 'Dark Navy')], default='#ca8a04', max_length=30, verbose_name='Card 3 — Icon Colour'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac3_desc',
            field=models.CharField(blank=True, default='Thousands of books, e-resources and quiet study spaces available daily.', max_length=300, verbose_name='Card 3 — Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac3_icon',
            field=models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-users', 'Group / Students'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-microscope', 'Science Lab'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-shield-halved', 'Excellence / Discipline'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-award', 'Award / Recognition'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry'), ('fa-solid fa-atom', 'Physics'), ('fa-solid fa-dna', 'Biology'), ('fa-solid fa-language', 'Languages'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-earth-asia', 'General Knowledge'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-door-open', 'Admissions'), ('fa-solid fa-file-pen', 'Exams / Tests')], default='fa-solid fa-book-open', max_length=100, verbose_name='Card 3 — Icon'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac3_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Card 3 — Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac3_title',
            field=models.CharField(blank=True, default='Digital Library', max_length=200, verbose_name='Card 3 — Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac3_url',
            field=models.CharField(blank=True, default='/facilities/', max_length=255, verbose_name='Card 3 — Link URL'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac4_color',
            field=models.CharField(blank=True, choices=[('', 'Gold (default)'), ('#1565c0', 'Blue'), ('#16a34a', 'Green'), ('#ca8a04', 'Amber / Yellow'), ('#ec407a', 'Pink / Red'), ('#ab47bc', 'Purple'), ('#0097a7', 'Teal / Cyan'), ('#e65100', 'Orange'), ('#1f1741', 'Dark Navy')], default='#ec407a', max_length=30, verbose_name='Card 4 — Icon Colour'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac4_desc',
            field=models.CharField(blank=True, default='Cricket, football, basketball and indoor games — PE taken seriously.', max_length=300, verbose_name='Card 4 — Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac4_icon',
            field=models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-users', 'Group / Students'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-microscope', 'Science Lab'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-shield-halved', 'Excellence / Discipline'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-award', 'Award / Recognition'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry'), ('fa-solid fa-atom', 'Physics'), ('fa-solid fa-dna', 'Biology'), ('fa-solid fa-language', 'Languages'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-earth-asia', 'General Knowledge'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-door-open', 'Admissions'), ('fa-solid fa-file-pen', 'Exams / Tests')], default='fa-solid fa-person-running', max_length=100, verbose_name='Card 4 — Icon'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac4_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Card 4 — Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac4_title',
            field=models.CharField(blank=True, default='Sports Grounds', max_length=200, verbose_name='Card 4 — Title'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='fac4_url',
            field=models.CharField(blank=True, default='/facilities/', max_length=255, verbose_name='Card 4 — Link URL'),
        ),
    ]
