# Generated by Django 6.0.3 on 2026-06-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_homepage_benefits_subtitle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursecard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='coursecard',
            name='page',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='benefits_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='benefits_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blog_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='blog_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='courses_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='courses_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='footer_newsletter_heading',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='journey_btn_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='journey_btn_url',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='journey_logo',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='journey_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='journey_title',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='CourseCard',
        ),
    ]
