# Generated by Django 6.0.3 on 2026-06-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_coursecard_image_remove_coursecard_page_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_mission_icon',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_mission_icon_class',
            field=models.CharField(blank=True, choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-users', 'Group / Students'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-microscope', 'Science Lab'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-shield-halved', 'Excellence / Discipline'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-award', 'Award / Recognition'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry'), ('fa-solid fa-atom', 'Physics'), ('fa-solid fa-dna', 'Biology'), ('fa-solid fa-language', 'Languages'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-earth-asia', 'General Knowledge'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-door-open', 'Admissions'), ('fa-solid fa-file-pen', 'Exams / Tests')], default='fa-solid fa-star-and-crescent', help_text='Icon displayed in the mission box.  e.g.  Star & Crescent for Islamic values.', max_length=100, verbose_name='Mission Icon'),
        ),
    ]
