# Generated by Django 6.0.3 on 2026-06-07 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_icon_dropdowns_everywhere'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=30, verbose_name='Phone')),
                ('dob', models.CharField(blank=True, max_length=30, verbose_name='Date of Birth')),
                ('campus', models.CharField(max_length=200, verbose_name='Campus')),
                ('board', models.CharField(max_length=200, verbose_name='Board')),
                ('class_level', models.CharField(max_length=100, verbose_name='Class')),
                ('message', models.TextField(blank=True, verbose_name='Message / Goals')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('is_read', models.BooleanField(default=False, verbose_name='Marked as Read')),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
