# Generated by Django 6.0.3 on 2026-06-09 17:21

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_admission_application_model'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='cta_btn_label',
            field=models.CharField(blank=True, default='Apply for Admission', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_btn_url',
            field=models.CharField(blank=True, default='/admissions/', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_heading',
            field=models.CharField(blank=True, default='Ready to Join the Azeem Family?', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_outline_label',
            field=models.CharField(blank=True, default='Contact Us', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='cta_outline_url',
            field=models.CharField(blank=True, default='/contact/', max_length=255),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_heading',
            field=models.CharField(blank=True, default='Our Mission', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mv_label',
            field=models.CharField(blank=True, default='Our Purpose', max_length=100, verbose_name='Section Label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mv_title',
            field=models.CharField(blank=True, default='Mission & Vision', max_length=300, verbose_name='Section Heading'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_label',
            field=models.CharField(blank=True, default='What We Stand For', max_length=100, verbose_name='Values Section Label'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='values_title',
            field=models.CharField(blank=True, default='Our Core Values', max_length=300, verbose_name='Values Section Heading'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_heading',
            field=models.CharField(blank=True, default='See Our Campus in Action', max_length=300),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_label',
            field=models.CharField(blank=True, default='Watch & Learn', max_length=100),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_video_thumbnail', to='wagtailimages.image', verbose_name='Video Thumbnail (shown if no YouTube ID set)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video_youtube_id',
            field=models.CharField(blank=True, help_text='Paste just the video ID from the URL — e.g. for https://youtu.be/dQw4w9WgXcQ paste dQw4w9WgXcQ', max_length=30, verbose_name='YouTube Video ID'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_heading',
            field=models.CharField(blank=True, default='Our Vision', max_length=200),
        ),
        migrations.CreateModel(
            name='AboutCoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_class', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book Closed'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry / Lab'), ('fa-solid fa-atom', 'Physics / Atom'), ('fa-solid fa-microscope', 'Science Lab / Microscope'), ('fa-solid fa-dna', 'Biology / DNA'), ('fa-solid fa-bolt', 'Electricity / Electronics'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-laptop-code', 'Coding / Programming'), ('fa-solid fa-microchip', 'Robotics / Microchip'), ('fa-solid fa-language', 'Languages / English'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-pen-to-square', 'Editing / Exams'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-star-and-crescent', 'Islamic / Crescent'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-earth-asia', 'Geography / GK'), ('fa-solid fa-map', 'Social Studies / Map'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-seedling', 'Early Years / Nursery'), ('fa-solid fa-child-reaching', 'Primary / Children'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Fitness'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-ranking-star', 'Rankings / Top Scorer'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-chalkboard-user', 'Teacher / Lecture'), ('fa-solid fa-users', 'Students / Group'), ('fa-solid fa-user-graduate', 'Graduate Student'), ('fa-solid fa-user-tie', 'Principal / Admin'), ('fa-solid fa-people-group', 'Community / Assembly'), ('fa-solid fa-handshake', 'Partnership / Trust'), ('fa-solid fa-hands-holding-child', 'Child Support'), ('fa-solid fa-door-open', 'Admissions / Open Door'), ('fa-solid fa-file-pen', 'Exams / Test Paper'), ('fa-solid fa-file-circle-check', 'Application Approved'), ('fa-solid fa-clipboard-list', 'Checklist / Requirements'), ('fa-solid fa-clipboard-check', 'Verification / Check'), ('fa-solid fa-id-card', 'Student ID'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-calendar-days', 'Academic Calendar'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-building-columns', 'Library / Hall'), ('fa-solid fa-utensils', 'Cafeteria / Canteen'), ('fa-solid fa-bus', 'School Transport'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-shield-halved', 'Security / Discipline'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Safety'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-heart-pulse', 'Wellbeing / Health'), ('fa-solid fa-hand-holding-heart', 'Caring Environment'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-circle-check', 'Verified / Certified'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-bell', 'Notice / Alert'), ('fa-solid fa-envelope', 'Email / Letter'), ('fa-solid fa-phone', 'Phone / Contact'), ('fa-solid fa-comment-dots', 'Message / Chat'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-info-circle', 'Information'), ('fa-solid fa-question-circle', 'FAQ / Help'), ('fa-solid fa-link', 'Link / Resource')], default='fa-solid fa-star', max_length=100, verbose_name='Icon')),
                ('label', models.CharField(max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutMissionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=300)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_points', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AboutVisionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=300)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='vision_points', to='home.aboutpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
