# Generated by Django 6.0.3 on 2026-06-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_about_page_video_mv_values_cta'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='choose_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
