# Generated by Django 6.0.3 on 2026-06-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_about_choose_description'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='banner_bg_image',
            field=models.ForeignKey(blank=True, help_text='Recommended resolution: 1920 × 486 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_banner_bg', to='wagtailimages.image', verbose_name='Banner Background Image'),
        ),
    ]
