# Generated by Django 6.0.3 on 2026-06-10 05:11

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_about_banner_bg_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='faq_heading',
            field=models.CharField(blank=True, default='Frequently Asked Questions', max_length=300),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='faq_label',
            field=models.CharField(blank=True, default='Common Questions', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='form_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hours_heading',
            field=models.CharField(blank=True, default="When We're Open", max_length=300),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hours_label',
            field=models.CharField(blank=True, default='School Hours', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_heading',
            field=models.CharField(blank=True, default='Visit Our Campus', max_length=300),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_label',
            field=models.CharField(blank=True, default='Find Us', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_link_label',
            field=models.CharField(blank=True, default='Open in Google Maps', max_length=100),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='map_link_url',
            field=models.URLField(blank=True, verbose_name="Google Maps Link URL (for 'Open in Maps' button)"),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='social_facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='social_instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='social_twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='social_whatsapp_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='social_youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_bg_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_form_bg', to='wagtailimages.image', verbose_name='Form Section Background Image'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_subtitle',
            field=models.CharField(default='Get In Touch', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='form_title',
            field=models.CharField(default='Send Us a Message', max_length=200),
        ),
        migrations.CreateModel(
            name='ContactFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('question', models.CharField(max_length=400)),
                ('answer', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_faqs', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('day', models.CharField(help_text='e.g. "Monday – Friday"', max_length=100)),
                ('time', models.CharField(help_text='e.g. "8:00 AM – 3:00 PM"', max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_hours', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
