# Generated by Django 6.0.3 on 2026-06-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_contact_page_enhanced'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactpage',
            name='form_bg_image',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_description',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_subtitle',
        ),
        migrations.RemoveField(
            model_name='contactpage',
            name='form_title',
        ),
    ]
