# Generated by Django 6.0.3 on 2026-06-10 05:29

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_contact_remove_form_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('counter', models.CharField(help_text='e.g. "3500"', max_length=20)),
                ('suffix', models.CharField(blank=True, help_text='e.g. "%", "+"', max_length=5)),
                ('label', models.CharField(max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_stats', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
