# Generated by Django 6.0.3 on 2026-06-10 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_contact_stats_strip'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='hours_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='hours_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_hours_image', to='wagtailimages.image', verbose_name='Hours Section Image'),
        ),
    ]
