# Generated by Django 6.0.3 on 2026-06-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_contact_hours_description_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpage',
            name='contact_info_description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
