# Generated by Django 6.0.3 on 2026-06-10 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_contact_info_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_btn_label',
            field=models.CharField(blank=True, default='Read More', max_length=50),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_btn_url',
            field=models.CharField(blank=True, default='./about.html', max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_heading',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='about_subtitle',
            field=models.CharField(blank=True, default='About Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='banner_title',
            field=models.CharField(blank=True, default='About Us', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='benefit_heading',
            field=models.CharField(blank=True, default='Benefits of Learning With Us', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='benefit_subtitle',
            field=models.CharField(blank=True, default='Our Expertise', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='choose_heading',
            field=models.CharField(blank=True, default='Why You Should Choose Us', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='choose_subtitle',
            field=models.CharField(blank=True, default='Our Features', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_about_title',
            field=models.CharField(blank=True, default='About Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_contact_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_contact_title',
            field=models.CharField(blank=True, default='Contact Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_explore_title',
            field=models.CharField(blank=True, default='Explore', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_links_title',
            field=models.CharField(blank=True, default='Useful Links', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_newsletter_heading',
            field=models.CharField(blank=True, default='Sign up for the newsletter:', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='nav_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_heading',
            field=models.CharField(blank=True, default='Our Skilled Instructors', max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='team_subtitle',
            field=models.CharField(blank=True, default='Instructors', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='testimonials_heading',
            field=models.CharField(blank=True, default="Student's Say About Us", max_length=300),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='testimonials_subtitle',
            field=models.CharField(blank=True, default='Reviews', max_length=100),
        ),
        migrations.AlterField(
            model_name='abouttestimonial',
            name='role',
            field=models.CharField(blank=True, default='Happy Student', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicachievementcard',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book', 'Book (closed)'), ('fa-solid fa-book-open', 'Book (open)'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Calculator / Maths'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-microscope', 'Microscope / Science'), ('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-bolt', 'Bolt / Electricity'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-language', 'Language / English'), ('fa-solid fa-pen-nib', 'Pen / Urdu Writing'), ('fa-solid fa-pen-to-square', 'Edit / Exam'), ('fa-solid fa-palette', 'Art & Craft'), ('fa-solid fa-map', 'Map / Social Studies'), ('fa-solid fa-flag', 'Flag / Pakistan Studies'), ('fa-solid fa-moon', 'Moon / Islamic Studies'), ('fa-solid fa-seedling', 'Seedling / Early Years'), ('fa-solid fa-person-running', 'Physical Education'), ('fa-solid fa-heart', 'Heart / Moral Education'), ('fa-solid fa-earth-asia', 'Globe / General Knowledge'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-clipboard-check', 'Clipboard Check'), ('fa-solid fa-file-pen', 'File Pen / Test'), ('fa-solid fa-file-invoice', 'File / Document'), ('fa-solid fa-list-check', 'List / Book List'), ('fa-solid fa-file-arrow-down', 'File Download'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-leaf', 'Leaf / Autumn Term'), ('fa-solid fa-snowflake', 'Snowflake / Winter'), ('fa-solid fa-sun', 'Sun / Summer'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea'), ('fa-solid fa-users', 'Users / Group'), ('fa-solid fa-chalkboard-user', 'Teacher'), ('fa-solid fa-school', 'School Building')], default='fa-solid fa-trophy', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicachievementcard',
            name='title',
            field=models.CharField(blank=True, default='Achievement Highlight', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicachievementstat',
            name='label',
            field=models.CharField(blank=True, default='Overall Pass Rate', max_length=150),
        ),
        migrations.AlterField(
            model_name='academicachievementstat',
            name='number',
            field=models.CharField(blank=True, default='98', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicassessment',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-yellow', 'Yellow / Amber'), ('icon-pink', 'Pink / Red'), ('icon-purple', 'Purple'), ('icon-cyan', 'Cyan / Teal'), ('icon-orange', 'Orange'), ('icon-dark', 'Dark Navy + Accent')], default='icon-blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicassessment',
            name='title',
            field=models.CharField(blank=True, default='Assessment Type', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicassessment',
            name='weight',
            field=models.CharField(blank=True, default='20%', help_text='Weightage badge text, e.g. "20% Weightage"', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicboard',
            name='border_color',
            field=models.CharField(blank=True, choices=[('soft-blue', 'Soft Blue (primary)'), ('accent', 'Lime / Accent (highlight)')], default='soft-blue', help_text='Left border colour of this board card', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicboard',
            name='name',
            field=models.CharField(blank=True, default='Board Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='academiccalendarterm',
            name='badge_label',
            field=models.CharField(blank=True, default='Term 1', help_text='Lime badge label, e.g. "Term 1", "Break", "Finals"', max_length=50),
        ),
        migrations.AlterField(
            model_name='academiccalendarterm',
            name='date_range',
            field=models.CharField(blank=True, default='Sep 2 – Nov 15', max_length=100),
        ),
        migrations.AlterField(
            model_name='academiccalendarterm',
            name='title',
            field=models.CharField(blank=True, default='Autumn Term', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicdownload',
            name='description',
            field=models.CharField(blank=True, default='PDF · 1 MB', help_text='e.g. "Complete syllabus for all classes · PDF · 1.2 MB"', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicdownload',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-yellow', 'Yellow / Amber'), ('icon-pink', 'Pink / Red'), ('icon-purple', 'Purple'), ('icon-cyan', 'Cyan / Teal'), ('icon-orange', 'Orange'), ('icon-dark', 'Dark Navy + Accent')], default='icon-blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicdownload',
            name='title',
            field=models.CharField(blank=True, default='Document Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicfaculty',
            name='avatar_color',
            field=models.CharField(blank=True, choices=[('#6a52e0', 'Purple'), ('#52b788', 'Green'), ('#f4b942', 'Yellow / Amber'), ('#ec407a', 'Pink'), ('#ab47bc', 'Violet'), ('#26c6da', 'Cyan'), ('#42a5f5', 'Blue'), ('#ff7043', 'Orange'), ('#1f1741', 'Dark Navy')], default='#6a52e0', help_text='Avatar circle background colour', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicfaculty',
            name='avatar_initial',
            field=models.CharField(blank=True, default='A', help_text='1–2 letters displayed in the avatar circle', max_length=2),
        ),
        migrations.AlterField(
            model_name='academicfaculty',
            name='name',
            field=models.CharField(blank=True, default='Faculty Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicfaculty',
            name='subject',
            field=models.CharField(blank=True, default='Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicgradeladderitem',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('gl-accent', 'Lime / Accent'), ('gl-blue', 'Blue / Purple'), ('gl-green', 'Green'), ('gl-yellow', 'Yellow'), ('gl-pink', 'Pink'), ('gl-purple', 'Violet'), ('gl-cyan', 'Cyan')], default='gl-blue', help_text='Icon colour on dark-navy background', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicgradeladderitem',
            name='subtitle',
            field=models.CharField(blank=True, default='', help_text='e.g. "Class 1 – Class 5"', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicgradeladderitem',
            name='title',
            field=models.CharField(blank=True, default='Grade Level', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='achievements_heading',
            field=models.CharField(blank=True, default='A Proven Track Record', max_length=300),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='achievements_subtitle',
            field=models.CharField(blank=True, default='Results & Achievements', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='assessments_heading',
            field=models.CharField(blank=True, default='How We Evaluate Progress', max_length=300),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='assessments_subtitle',
            field=models.CharField(blank=True, default='Assessments', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='banner_title',
            field=models.CharField(blank=True, default='Academics', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='calendar_heading',
            field=models.CharField(blank=True, default='Academic Calendar', max_length=300),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='calendar_subtitle',
            field=models.CharField(blank=True, default='Academic Year 2024–25', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='cta_button_label',
            field=models.CharField(blank=True, default='Apply for Admission', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='cta_button_url',
            field=models.CharField(blank=True, default='/admissions/', max_length=255),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='cta_heading',
            field=models.CharField(blank=True, default='Ready to Enrol Your Child?', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='curriculum_heading',
            field=models.CharField(blank=True, default='A Structured Path to Excellence', max_length=300),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='curriculum_subtitle',
            field=models.CharField(blank=True, default='Curriculum & Board', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='downloads_heading',
            field=models.CharField(blank=True, default='Downloads & Resources', max_length=300),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='downloads_subtitle',
            field=models.CharField(blank=True, default='Resources', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='faculty_heading',
            field=models.CharField(blank=True, default='Meet the Faculty', max_length=300),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='faculty_subtitle',
            field=models.CharField(blank=True, default='Our Educators', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='footer_about_title',
            field=models.CharField(blank=True, default='About Azeem School', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='footer_contact_address',
            field=models.CharField(blank=True, default='KDA Scheme, Karachi, Pakistan', max_length=300),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='footer_contact_phone',
            field=models.CharField(blank=True, default='+92 21 3456 7890', max_length=30),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='footer_contact_title',
            field=models.CharField(blank=True, default='Contact Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='© 2025 Azeem School. All Rights Reserved.', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='footer_explore_title',
            field=models.CharField(blank=True, default='Academics', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='footer_links_title',
            field=models.CharField(blank=True, default='Quick Links', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='footer_newsletter_heading',
            field=models.CharField(blank=True, default='Subscribe to Our Newsletter', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='grade_ladder_heading',
            field=models.CharField(blank=True, default='From First Steps to Board Exams', max_length=200),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='grade_ladder_subtitle',
            field=models.CharField(blank=True, default='Grade Structure', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='nav_login_label',
            field=models.CharField(blank=True, default='Student Portal', max_length=50),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='nav_login_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='nav_phone',
            field=models.CharField(blank=True, default='+92 21 3456 7890', max_length=30),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='subjects_heading',
            field=models.CharField(blank=True, default='What Your Child Will Learn', max_length=300),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='subjects_subtitle',
            field=models.CharField(blank=True, default='Subjects', max_length=100),
        ),
        migrations.AlterField(
            model_name='academicstat',
            name='label',
            field=models.CharField(blank=True, default='Subjects Offered', max_length=150),
        ),
        migrations.AlterField(
            model_name='academicstat',
            name='number',
            field=models.CharField(blank=True, default='14', help_text='e.g. "14", "98", "25"', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicsubject',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-yellow', 'Yellow / Amber'), ('icon-pink', 'Pink / Red'), ('icon-purple', 'Purple'), ('icon-cyan', 'Cyan / Teal'), ('icon-orange', 'Orange'), ('icon-dark', 'Dark Navy + Accent')], default='icon-blue', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicsubject',
            name='level',
            field=models.CharField(blank=True, choices=[('early_years', 'Early Years (Pre-Mon, Mon, KG1, KG2)'), ('primary', 'Primary (Class 1–5)'), ('middle', 'Middle (Class 6–8)'), ('secondary', 'Secondary (Class 9–10)')], default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='academicsubject',
            name='name',
            field=models.CharField(blank=True, default='Subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionintakecard',
            name='bg_choice',
            field=models.CharField(blank=True, choices=[('bg1', 'Green (bg1)'), ('bg2', 'Yellow (bg2)'), ('bg3', 'Red (bg3)')], default='bg1', max_length=10),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='banner_title',
            field=models.CharField(blank=True, default='Start Your Journey With Us', max_length=200),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_about_title',
            field=models.CharField(blank=True, default='About Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_contact_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_contact_title',
            field=models.CharField(blank=True, default='Contact Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_explore_title',
            field=models.CharField(blank=True, default='Programs', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_links_title',
            field=models.CharField(blank=True, default='Useful Links', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_newsletter_heading',
            field=models.CharField(blank=True, default='Sign up for the newsletter:', max_length=200),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='form_heading',
            field=models.CharField(blank=True, default='Your Future Starts With One Form', max_length=300),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='form_submit_label',
            field=models.CharField(blank=True, default='Submit My Application', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='form_subtitle',
            field=models.CharField(blank=True, default='Apply Now', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='nav_login_label',
            field=models.CharField(blank=True, default='Log In', max_length=50),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='nav_login_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='nav_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='process_heading',
            field=models.CharField(blank=True, default='How Our Admissions Works', max_length=300),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='process_subtitle',
            field=models.CharField(blank=True, default='Simple & Fast', max_length=100),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='requirements_heading',
            field=models.CharField(blank=True, default='Eligibility & Requirements', max_length=300),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='requirements_subtitle',
            field=models.CharField(blank=True, default='Who Can Apply', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='banner_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='banner_title',
            field=models.CharField(blank=True, default='Contact Us', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_info_subtitle',
            field=models.CharField(blank=True, default='Contact Info', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='contact_info_title',
            field=models.CharField(blank=True, default='Our Contact Information', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='email_1',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_about_title',
            field=models.CharField(blank=True, default='About Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_contact_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_contact_title',
            field=models.CharField(blank=True, default='Contact Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_explore_title',
            field=models.CharField(blank=True, default='Explore', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_links_title',
            field=models.CharField(blank=True, default='Useful Links', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_newsletter_heading',
            field=models.CharField(blank=True, default='Sign up for the newsletter:', max_length=200),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='hours_description',
            field=models.TextField(blank=True, default='Our campus is open throughout the week for classes, administrative support, and parent visits. Below is our weekly schedule.'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='location_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='nav_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='phone_1',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='arts_heading',
            field=models.CharField(blank=True, default='Arts & Performing Arts Spaces', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='arts_subtitle',
            field=models.CharField(blank=True, default='Creative Expression', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='banner_title',
            field=models.CharField(blank=True, default='Our Facilities', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='cta_btn_label',
            field=models.CharField(blank=True, default='Book a Campus Tour', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='cta_btn_url',
            field=models.CharField(blank=True, default='/contact/', max_length=255),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='cta_heading',
            field=models.CharField(blank=True, default='Come See It for Yourself', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='cta_outline_label',
            field=models.CharField(blank=True, default='Apply Now', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='cta_outline_url',
            field=models.CharField(blank=True, default='/admissions/', max_length=255),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='footer_about_title',
            field=models.CharField(blank=True, default='About Azeem School', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='footer_contact_address',
            field=models.CharField(blank=True, default='Main Campus, Azeem Road, Karachi', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='footer_contact_phone',
            field=models.CharField(blank=True, default='+92 21 3456 7890', max_length=30),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='footer_contact_title',
            field=models.CharField(blank=True, default='Contact Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='© 2025 Azeem School. All Rights Reserved.', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='footer_explore_title',
            field=models.CharField(blank=True, default='Explore', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='footer_links_title',
            field=models.CharField(blank=True, default='Quick Links', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='footer_newsletter_heading',
            field=models.CharField(blank=True, default='Stay Connected with Azeem School', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='gallery_heading',
            field=models.CharField(blank=True, default='A Glimpse of Azeem School', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='gallery_subtitle',
            field=models.CharField(blank=True, default='Campus Life', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='labs_heading',
            field=models.CharField(blank=True, default='State-of-the-Art Laboratories', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='labs_subtitle',
            field=models.CharField(blank=True, default='Hands-On Learning', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='library_heading',
            field=models.CharField(blank=True, default='Library & Resource Centre', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='library_panel_eyebrow',
            field=models.CharField(blank=True, default='Library at a Glance', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='library_panel_heading',
            field=models.CharField(blank=True, default='A World of Knowledge, One Shelf Away', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='library_subtitle',
            field=models.CharField(blank=True, default='Knowledge Hub', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='nav_login_label',
            field=models.CharField(blank=True, default='Student Portal', max_length=50),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='nav_login_url',
            field=models.CharField(blank=True, default='#', max_length=255),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='nav_phone',
            field=models.CharField(blank=True, default='+92 21 3456 7890', max_length=30),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='overview_heading',
            field=models.CharField(blank=True, default='Everything a Modern School Should Have', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='overview_subtitle',
            field=models.CharField(blank=True, default='What We Offer', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='safety_eyebrow',
            field=models.CharField(blank=True, default="Your Child's Safety First", max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='safety_heading',
            field=models.CharField(blank=True, default='Health, Safety & Welfare', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='sports_heading',
            field=models.CharField(blank=True, default='Sports & Athletics Facilities', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='sports_subtitle',
            field=models.CharField(blank=True, default='Active & Healthy', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='tour_btn_label',
            field=models.CharField(blank=True, default='Book a Live Campus Visit', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='tour_btn_url',
            field=models.CharField(blank=True, default='/contact/', max_length=255),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='tour_eyebrow',
            field=models.CharField(blank=True, default='Virtual Campus Tour', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='tour_heading',
            field=models.CharField(blank=True, default='See Every Corner of Our Campus', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilityartscard',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-music', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilityartscard',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-teal', 'Teal'), ('icon-purple', 'Purple'), ('icon-orange', 'Orange'), ('icon-yellow', 'Yellow'), ('icon-pink', 'Pink'), ('icon-cyan', 'Cyan')], default='icon-pink', help_text='Icon background colour theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='facilityartscard',
            name='title',
            field=models.CharField(blank=True, default='Arts Space Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilityherocard',
            name='badge_icon',
            field=models.CharField(blank=True, choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-school', help_text='Icon inside the lime badge', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilityherocard',
            name='badge_label',
            field=models.CharField(blank=True, default='Facility Name', help_text='Badge text, e.g. "Science & Labs"', max_length=80),
        ),
        migrations.AlterField(
            model_name='facilityherocard',
            name='description',
            field=models.CharField(blank=True, default='Short description for this facility area', help_text='One-line description shown beneath the title', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilityherocard',
            name='title',
            field=models.CharField(blank=True, default='Facility Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitylab',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-flask', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitylab',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-teal', 'Teal'), ('icon-purple', 'Purple'), ('icon-orange', 'Orange'), ('icon-yellow', 'Yellow'), ('icon-pink', 'Pink'), ('icon-cyan', 'Cyan')], default='icon-blue', help_text='Icon background colour theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='facilitylab',
            name='title',
            field=models.CharField(blank=True, default='Lab Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitylibraryfeature',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-book-open', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitylibraryfeature',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-teal', 'Teal'), ('icon-purple', 'Purple'), ('icon-orange', 'Orange'), ('icon-yellow', 'Yellow'), ('icon-pink', 'Pink'), ('icon-cyan', 'Cyan')], default='icon-green', max_length=20),
        ),
        migrations.AlterField(
            model_name='facilitylibraryfeature',
            name='title',
            field=models.CharField(blank=True, default='Feature Title', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitylibrarystat',
            name='label',
            field=models.CharField(blank=True, default='Books and reference volumes', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitylibrarystat',
            name='number',
            field=models.CharField(blank=True, default='25K+', help_text='The number displayed, e.g. "25K+", "3,500", "4", "6 AM"', max_length=30),
        ),
        migrations.AlterField(
            model_name='facilityoverviewtile',
            name='description',
            field=models.CharField(blank=True, default='Short description of this facility area.', max_length=250),
        ),
        migrations.AlterField(
            model_name='facilityoverviewtile',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-school', help_text='Font Awesome icon class', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilityoverviewtile',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('icon-blue', 'Blue'), ('icon-green', 'Green'), ('icon-teal', 'Teal'), ('icon-purple', 'Purple'), ('icon-orange', 'Orange'), ('icon-yellow', 'Yellow'), ('icon-pink', 'Pink'), ('icon-cyan', 'Cyan')], default='icon-blue', help_text='Icon background colour theme', max_length=20),
        ),
        migrations.AlterField(
            model_name='facilityoverviewtile',
            name='title',
            field=models.CharField(blank=True, default='Facility Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitysafetycard',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-shield-halved', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitysafetycard',
            name='title',
            field=models.CharField(blank=True, default='Safety Feature', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitysafetystat',
            name='label',
            field=models.CharField(blank=True, default='CCTV Cameras on Campus', max_length=150),
        ),
        migrations.AlterField(
            model_name='facilitysafetystat',
            name='number',
            field=models.CharField(blank=True, default='120+', help_text='e.g. "120+", "24/7", "2", "100%"', max_length=20),
        ),
        migrations.AlterField(
            model_name='facilitysmallcard',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-school', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitysmallcard',
            name='subtitle',
            field=models.CharField(blank=True, default='Short detail line', help_text='Short line below title, e.g. "25,000+ volumes"', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitysmallcard',
            name='title',
            field=models.CharField(blank=True, default='Facility', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitysport',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-futbol', help_text='Icon shown at the top of the sport card', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitysport',
            name='title',
            field=models.CharField(blank=True, default='Sport / Facility Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='facilitystat',
            name='label',
            field=models.CharField(blank=True, default='Square Feet Campus', max_length=150),
        ),
        migrations.AlterField(
            model_name='facilitystat',
            name='number',
            field=models.CharField(blank=True, default='50', help_text='Numeric value, e.g. "50", "12", "25"', max_length=20),
        ),
        migrations.AlterField(
            model_name='facilitytourbullet',
            name='description',
            field=models.CharField(blank=True, default='Brief description of this tour highlight', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitytourbullet',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-atom', 'Atom / Physics'), ('fa-solid fa-flask', 'Flask / Chemistry'), ('fa-solid fa-flask-vial', 'Flask Vial'), ('fa-solid fa-dna', 'DNA / Biology'), ('fa-solid fa-microscope', 'Microscope'), ('fa-solid fa-laptop-code', 'Laptop Code / Computer'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-microchip', 'Microchip / Robotics'), ('fa-solid fa-robot', 'Robot / STEM'), ('fa-solid fa-language', 'Language Lab'), ('fa-solid fa-print', '3D Printer / Print'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-person-running', 'Athletics / Running'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Weights'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book'), ('fa-solid fa-tablet-screen-button', 'Digital / Tablet'), ('fa-solid fa-users', 'Group / Team'), ('fa-solid fa-mug-saucer', 'Lounge / Reading'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-palette', 'Art / Painting'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-video', 'Media / Video'), ('fa-solid fa-microphone', 'Microphone / Podcast'), ('fa-solid fa-shield-halved', 'Shield / Security'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-utensils', 'Cafeteria / Food'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Camera'), ('fa-solid fa-heart-pulse', 'Health / Pulse'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-circle-check', 'Circle Check'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-lightbulb', 'Lightbulb / Idea')], default='fa-solid fa-school', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitytourbullet',
            name='title',
            field=models.CharField(blank=True, default='What You Will See', max_length=150),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_subtitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='boards_subtitle',
            field=models.CharField(blank=True, default='Academic Programs', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='boards_title',
            field=models.CharField(blank=True, default='Boards We Follow', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='fac1_icon',
            field=models.CharField(blank=True, choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book Closed'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry / Lab'), ('fa-solid fa-atom', 'Physics / Atom'), ('fa-solid fa-microscope', 'Science Lab / Microscope'), ('fa-solid fa-dna', 'Biology / DNA'), ('fa-solid fa-bolt', 'Electricity / Electronics'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-laptop-code', 'Coding / Programming'), ('fa-solid fa-microchip', 'Robotics / Microchip'), ('fa-solid fa-language', 'Languages / English'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-pen-to-square', 'Editing / Exams'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-star-and-crescent', 'Islamic / Crescent'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-earth-asia', 'Geography / GK'), ('fa-solid fa-map', 'Social Studies / Map'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-seedling', 'Early Years / Nursery'), ('fa-solid fa-child-reaching', 'Primary / Children'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Fitness'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-ranking-star', 'Rankings / Top Scorer'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-chalkboard-user', 'Teacher / Lecture'), ('fa-solid fa-users', 'Students / Group'), ('fa-solid fa-user-graduate', 'Graduate Student'), ('fa-solid fa-user-tie', 'Principal / Admin'), ('fa-solid fa-people-group', 'Community / Assembly'), ('fa-solid fa-handshake', 'Partnership / Trust'), ('fa-solid fa-hands-holding-child', 'Child Support'), ('fa-solid fa-door-open', 'Admissions / Open Door'), ('fa-solid fa-file-pen', 'Exams / Test Paper'), ('fa-solid fa-file-circle-check', 'Application Approved'), ('fa-solid fa-clipboard-list', 'Checklist / Requirements'), ('fa-solid fa-clipboard-check', 'Verification / Check'), ('fa-solid fa-id-card', 'Student ID'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-calendar-days', 'Academic Calendar'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-building-columns', 'Library / Hall'), ('fa-solid fa-utensils', 'Cafeteria / Canteen'), ('fa-solid fa-bus', 'School Transport'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-shield-halved', 'Security / Discipline'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Safety'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-heart-pulse', 'Wellbeing / Health'), ('fa-solid fa-hand-holding-heart', 'Caring Environment'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-circle-check', 'Verified / Certified'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-bell', 'Notice / Alert'), ('fa-solid fa-envelope', 'Email / Letter'), ('fa-solid fa-phone', 'Phone / Contact'), ('fa-solid fa-comment-dots', 'Message / Chat'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-info-circle', 'Information'), ('fa-solid fa-question-circle', 'FAQ / Help'), ('fa-solid fa-link', 'Link / Resource')], default='fa-solid fa-computer', max_length=100, verbose_name='Card 1 — Icon'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='fac2_icon',
            field=models.CharField(blank=True, choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book Closed'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry / Lab'), ('fa-solid fa-atom', 'Physics / Atom'), ('fa-solid fa-microscope', 'Science Lab / Microscope'), ('fa-solid fa-dna', 'Biology / DNA'), ('fa-solid fa-bolt', 'Electricity / Electronics'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-laptop-code', 'Coding / Programming'), ('fa-solid fa-microchip', 'Robotics / Microchip'), ('fa-solid fa-language', 'Languages / English'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-pen-to-square', 'Editing / Exams'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-star-and-crescent', 'Islamic / Crescent'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-earth-asia', 'Geography / GK'), ('fa-solid fa-map', 'Social Studies / Map'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-seedling', 'Early Years / Nursery'), ('fa-solid fa-child-reaching', 'Primary / Children'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Fitness'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-ranking-star', 'Rankings / Top Scorer'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-chalkboard-user', 'Teacher / Lecture'), ('fa-solid fa-users', 'Students / Group'), ('fa-solid fa-user-graduate', 'Graduate Student'), ('fa-solid fa-user-tie', 'Principal / Admin'), ('fa-solid fa-people-group', 'Community / Assembly'), ('fa-solid fa-handshake', 'Partnership / Trust'), ('fa-solid fa-hands-holding-child', 'Child Support'), ('fa-solid fa-door-open', 'Admissions / Open Door'), ('fa-solid fa-file-pen', 'Exams / Test Paper'), ('fa-solid fa-file-circle-check', 'Application Approved'), ('fa-solid fa-clipboard-list', 'Checklist / Requirements'), ('fa-solid fa-clipboard-check', 'Verification / Check'), ('fa-solid fa-id-card', 'Student ID'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-calendar-days', 'Academic Calendar'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-building-columns', 'Library / Hall'), ('fa-solid fa-utensils', 'Cafeteria / Canteen'), ('fa-solid fa-bus', 'School Transport'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-shield-halved', 'Security / Discipline'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Safety'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-heart-pulse', 'Wellbeing / Health'), ('fa-solid fa-hand-holding-heart', 'Caring Environment'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-circle-check', 'Verified / Certified'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-bell', 'Notice / Alert'), ('fa-solid fa-envelope', 'Email / Letter'), ('fa-solid fa-phone', 'Phone / Contact'), ('fa-solid fa-comment-dots', 'Message / Chat'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-info-circle', 'Information'), ('fa-solid fa-question-circle', 'FAQ / Help'), ('fa-solid fa-link', 'Link / Resource')], default='fa-solid fa-microscope', max_length=100, verbose_name='Card 2 — Icon'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='fac3_icon',
            field=models.CharField(blank=True, choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book Closed'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry / Lab'), ('fa-solid fa-atom', 'Physics / Atom'), ('fa-solid fa-microscope', 'Science Lab / Microscope'), ('fa-solid fa-dna', 'Biology / DNA'), ('fa-solid fa-bolt', 'Electricity / Electronics'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-laptop-code', 'Coding / Programming'), ('fa-solid fa-microchip', 'Robotics / Microchip'), ('fa-solid fa-language', 'Languages / English'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-pen-to-square', 'Editing / Exams'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-star-and-crescent', 'Islamic / Crescent'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-earth-asia', 'Geography / GK'), ('fa-solid fa-map', 'Social Studies / Map'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-seedling', 'Early Years / Nursery'), ('fa-solid fa-child-reaching', 'Primary / Children'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Fitness'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-ranking-star', 'Rankings / Top Scorer'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-chalkboard-user', 'Teacher / Lecture'), ('fa-solid fa-users', 'Students / Group'), ('fa-solid fa-user-graduate', 'Graduate Student'), ('fa-solid fa-user-tie', 'Principal / Admin'), ('fa-solid fa-people-group', 'Community / Assembly'), ('fa-solid fa-handshake', 'Partnership / Trust'), ('fa-solid fa-hands-holding-child', 'Child Support'), ('fa-solid fa-door-open', 'Admissions / Open Door'), ('fa-solid fa-file-pen', 'Exams / Test Paper'), ('fa-solid fa-file-circle-check', 'Application Approved'), ('fa-solid fa-clipboard-list', 'Checklist / Requirements'), ('fa-solid fa-clipboard-check', 'Verification / Check'), ('fa-solid fa-id-card', 'Student ID'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-calendar-days', 'Academic Calendar'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-building-columns', 'Library / Hall'), ('fa-solid fa-utensils', 'Cafeteria / Canteen'), ('fa-solid fa-bus', 'School Transport'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-shield-halved', 'Security / Discipline'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Safety'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-heart-pulse', 'Wellbeing / Health'), ('fa-solid fa-hand-holding-heart', 'Caring Environment'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-circle-check', 'Verified / Certified'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-bell', 'Notice / Alert'), ('fa-solid fa-envelope', 'Email / Letter'), ('fa-solid fa-phone', 'Phone / Contact'), ('fa-solid fa-comment-dots', 'Message / Chat'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-info-circle', 'Information'), ('fa-solid fa-question-circle', 'FAQ / Help'), ('fa-solid fa-link', 'Link / Resource')], default='fa-solid fa-book-open', max_length=100, verbose_name='Card 3 — Icon'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='fac4_icon',
            field=models.CharField(blank=True, choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book Closed'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry / Lab'), ('fa-solid fa-atom', 'Physics / Atom'), ('fa-solid fa-microscope', 'Science Lab / Microscope'), ('fa-solid fa-dna', 'Biology / DNA'), ('fa-solid fa-bolt', 'Electricity / Electronics'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-laptop-code', 'Coding / Programming'), ('fa-solid fa-microchip', 'Robotics / Microchip'), ('fa-solid fa-language', 'Languages / English'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-pen-to-square', 'Editing / Exams'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-star-and-crescent', 'Islamic / Crescent'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-earth-asia', 'Geography / GK'), ('fa-solid fa-map', 'Social Studies / Map'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-seedling', 'Early Years / Nursery'), ('fa-solid fa-child-reaching', 'Primary / Children'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Fitness'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-ranking-star', 'Rankings / Top Scorer'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-chalkboard-user', 'Teacher / Lecture'), ('fa-solid fa-users', 'Students / Group'), ('fa-solid fa-user-graduate', 'Graduate Student'), ('fa-solid fa-user-tie', 'Principal / Admin'), ('fa-solid fa-people-group', 'Community / Assembly'), ('fa-solid fa-handshake', 'Partnership / Trust'), ('fa-solid fa-hands-holding-child', 'Child Support'), ('fa-solid fa-door-open', 'Admissions / Open Door'), ('fa-solid fa-file-pen', 'Exams / Test Paper'), ('fa-solid fa-file-circle-check', 'Application Approved'), ('fa-solid fa-clipboard-list', 'Checklist / Requirements'), ('fa-solid fa-clipboard-check', 'Verification / Check'), ('fa-solid fa-id-card', 'Student ID'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-calendar-days', 'Academic Calendar'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-building-columns', 'Library / Hall'), ('fa-solid fa-utensils', 'Cafeteria / Canteen'), ('fa-solid fa-bus', 'School Transport'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-shield-halved', 'Security / Discipline'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Safety'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-heart-pulse', 'Wellbeing / Health'), ('fa-solid fa-hand-holding-heart', 'Caring Environment'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-circle-check', 'Verified / Certified'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-bell', 'Notice / Alert'), ('fa-solid fa-envelope', 'Email / Letter'), ('fa-solid fa-phone', 'Phone / Contact'), ('fa-solid fa-comment-dots', 'Message / Chat'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-info-circle', 'Information'), ('fa-solid fa-question-circle', 'FAQ / Help'), ('fa-solid fa-link', 'Link / Resource')], default='fa-solid fa-person-running', max_length=100, verbose_name='Card 4 — Icon'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_about_title',
            field=models.CharField(blank=True, default='About Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_contact_address',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_contact_phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_contact_title',
            field=models.CharField(blank=True, default='Contact Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_copyright_text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_explore_title',
            field=models.CharField(blank=True, default='Explore', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_links_title',
            field=models.CharField(blank=True, default='Useful Links', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_btn_label',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Button Title'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_btn_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Headline'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_headline_2',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Headline 2 Optional'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_tagline',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Tagline'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_btn_label',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Button Label'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_btn_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='nav_phone',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='notices_subtitle',
            field=models.CharField(blank=True, default='Latest Updates', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='notices_title',
            field=models.CharField(blank=True, default='School Notices & Announcements', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonials_subtitle',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='testimonials_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='trust_btn_label',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Button Label'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='trust_btn_url',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Button URL'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='trust_heading',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Heading'),
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='ann_type',
            field=models.CharField(blank=True, choices=[('academic', 'Academic'), ('event', 'Event'), ('sports', 'Sports'), ('exam', 'Exam'), ('notice', 'Notice')], default='notice', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='badge_style',
            field=models.CharField(blank=True, choices=[('ab-event', 'Event (purple)'), ('ab-academic', 'Academic (blue)'), ('ab-sports', 'Sports (lime)'), ('ab-exam', 'Exam (orange)'), ('ab-notice', 'Notice (pink)')], default='ab-notice', help_text='Colour of the category badge pill', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='icon_choice',
            field=models.CharField(blank=True, choices=[('fa-solid fa-bell', 'Bell'), ('fa-solid fa-thumbtack', 'Pin / Thumbtack'), ('fa-solid fa-file-pen', 'File / Exam'), ('fa-solid fa-door-open', 'Admissions / Door'), ('fa-solid fa-trophy', 'Trophy / Achievement'), ('fa-solid fa-chalkboard-user', 'Parent-Teacher Meeting'), ('fa-solid fa-flask', 'Science / Lab'), ('fa-solid fa-futbol', 'Sports / Football'), ('fa-solid fa-bus', 'Transport / Bus'), ('fa-solid fa-calendar-days', 'Calendar / Schedule'), ('fa-solid fa-graduation-cap', 'Graduation / Results'), ('fa-solid fa-star', 'Achievement / Star'), ('fa-solid fa-bullhorn', 'Notice / Announcement'), ('fa-solid fa-book-open', 'Academics / Books'), ('fa-solid fa-music', 'Arts / Music'), ('fa-solid fa-heart-pulse', 'Health / Medical'), ('fa-solid fa-shield-halved', 'Safety / Security'), ('fa-solid fa-utensils', 'Cafeteria'), ('fa-solid fa-mosque', 'Prayer / Event'), ('fa-solid fa-award', 'Award / Recognition')], default='fa-solid fa-bell', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsannouncement',
            name='icon_style',
            field=models.CharField(blank=True, choices=[('ai-purple', 'Purple'), ('ai-lime', 'Lime / Accent'), ('ai-blue', 'Blue'), ('ai-pink', 'Pink'), ('ai-orange', 'Orange'), ('ai-teal', 'Teal')], default='ai-purple', help_text='Background colour of the icon box', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, choices=[('flagship', 'Flagship Event of the Year'), ('annual_day', 'Annual Day & Prize Distribution'), ('sports_day', 'Sports Day'), ('science_fair', 'Science Fair & Exhibition'), ('cultural', 'Cultural Festival'), ('graduation', 'Graduation Ceremony'), ('trip', 'Educational Trip & Excursion'), ('result', 'Board Results & Achievements'), ('exam_notice', 'Exam Schedule & Notice'), ('academic', 'Academic Update'), ('award', 'Award & Recognition'), ('olympiad', 'Olympiad & Competition'), ('cambridge', 'Cambridge / O-A Level'), ('sports', 'Sports & Athletics'), ('inter_school', 'Inter-School Tournament'), ('arts', 'Arts, Music & Drama'), ('debate', 'Debate & Public Speaking'), ('admissions', 'Admissions Open'), ('notice', 'Important Notice'), ('welfare', 'Student Welfare & Health'), ('community', 'Community & Social Work'), ('pakistan_day', 'Pakistan Day / National Event'), ('ramadan', 'Ramadan & Islamic Events'), ('staff', 'Staff & Faculty News')], default='event', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsgalleryphoto',
            name='category',
            field=models.CharField(blank=True, choices=[('events', 'Events'), ('sports', 'Sports'), ('arts', 'Arts'), ('campus', 'Campus'), ('academics', 'Academics')], default='events', max_length=20),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='ann_eyebrow',
            field=models.CharField(blank=True, default='Notice Board', max_length=100),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='ann_heading',
            field=models.CharField(blank=True, default='Announcements & Upcoming Events', max_length=200),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='banner_title',
            field=models.CharField(blank=True, default='News & Gallery', max_length=200),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='cta_heading',
            field=models.CharField(blank=True, default='Never Miss an Update', max_length=200),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='events_panel_heading',
            field=models.CharField(blank=True, default='Upcoming Events', max_length=100),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='gallery_eyebrow',
            field=models.CharField(blank=True, default='Campus Moments', max_length=100),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='gallery_heading',
            field=models.CharField(blank=True, default='School Gallery', max_length=200),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='news_eyebrow',
            field=models.CharField(blank=True, default="Editor's Pick", max_length=100),
        ),
        migrations.AlterField(
            model_name='newspage',
            name='news_heading',
            field=models.CharField(blank=True, default='Latest from Azeem School', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsupcomingevent',
            name='badge_type',
            field=models.CharField(blank=True, choices=[('upcoming', 'Upcoming'), ('today', 'Today / This Month')], default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(blank=True, default='Happy Client', max_length=100),
        ),
    ]
