# Generated by Django 6.0.3 on 2026-06-10 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_add_blank_true_all_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='about_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='banner_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='benefit_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_about_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='footer_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='academicachievementcard',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='academicassessment',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='academicboard',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='academicspage',
            name='footer_contact_email',
            field=models.EmailField(blank=True, default='info@azeem.edu.pk', max_length=254),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='banner_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_about_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='footer_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='form_contact_email',
            field=models.EmailField(blank=True, default='admissions@educiza.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='admissionspage',
            name='form_intro_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_about_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='contactpage',
            name='footer_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='facilitiespage',
            name='footer_contact_email',
            field=models.EmailField(blank=True, default='info@azeem.edu.pk', max_length=254),
        ),
        migrations.AlterField(
            model_name='facilityartscard',
            name='description',
            field=models.TextField(blank=True, default='Brief description of this creative space.'),
        ),
        migrations.AlterField(
            model_name='facilitylab',
            name='description',
            field=models.TextField(blank=True, default='Brief description of this laboratory.'),
        ),
        migrations.AlterField(
            model_name='facilitylibraryfeature',
            name='description',
            field=models.TextField(blank=True, default='Brief description of this library feature.'),
        ),
        migrations.AlterField(
            model_name='facilitysafetycard',
            name='description',
            field=models.TextField(blank=True, default='Description of this safety or welfare provision.'),
        ),
        migrations.AlterField(
            model_name='facilitysport',
            name='description',
            field=models.TextField(blank=True, default='Brief description of this sports facility.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='boards_description',
            field=models.TextField(blank=True, default='We follow the curriculum of top educational boards to ensure quality education for our students.'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_about_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='footer_contact_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='trust_description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
    ]
