# Generated by Django 6.0.3 on 2026-06-12 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_add_blank_true_first_arg'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='ad_popup_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable Popup'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ad_popup_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homepage_ad_popup', to='wagtailimages.image', verbose_name='Popup Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='ad_popup_link_url',
            field=models.URLField(blank=True, verbose_name='Click-through URL (optional)'),
        ),
    ]
