# Generated by Django 6.0.3 on 2026-06-12 06:08

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_homepage_ad_popup'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('headline', models.CharField(blank=True, default='', max_length=300, verbose_name='Headline (overrides page default)')),
                ('tagline', models.CharField(blank=True, default='', max_length=300, verbose_name='Tagline (overrides page default)')),
                ('btn_label', models.CharField(blank=True, default='', max_length=50, verbose_name='Button Label')),
                ('btn_url', models.CharField(blank=True, default='', max_length=255, verbose_name='Button URL')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Slide Background Image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_slides', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
