# Generated by Django 6.0.3 on 2026-06-24 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_hero_slides'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='alumni_form_email',
            field=models.EmailField(blank=True, default='', help_text='Submissions from the alumni form are sent to this address.', max_length=254, verbose_name='Alumni Form — Notification Email'),
        ),
    ]
