# Generated by Django 6.0.3 on 2026-06-25 11:38

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_aboutpage_alumni_form_email'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('banner_title', models.CharField(blank=True, default='Careers at Azeem School', max_length=200)),
                ('banner_description', models.TextField(blank=True, default='Shape the next generation. Join a team of passionate educators and staff committed to excellence.')),
                ('why_subtitle', models.CharField(blank=True, default='Why Azeem School', max_length=100)),
                ('why_heading', models.CharField(blank=True, default='A Place Where Educators Thrive', max_length=300)),
                ('positions_subtitle', models.CharField(blank=True, default='Current Openings', max_length=100)),
                ('positions_heading', models.CharField(blank=True, default='Open Positions', max_length=300)),
                ('positions_intro', models.TextField(blank=True, default="We welcome applications from passionate individuals. Submit your CV even if your position isn't listed — we keep strong candidates on file.")),
                ('howto_subtitle', models.CharField(blank=True, default='Application Process', max_length=100)),
                ('howto_heading', models.CharField(blank=True, default='How to Apply', max_length=300)),
                ('cta_heading', models.CharField(blank=True, default='Ready to Make a Difference?', max_length=200)),
                ('cta_description', models.TextField(blank=True, default="Can't find the right opening? Send us a general application and we'll keep your CV on file for future vacancies.")),
                ('cta_email', models.EmailField(blank=True, default='careers@azeemschool.edu.pk', max_length=254)),
                ('application_email', models.EmailField(blank=True, help_text='Receives career application form submissions. Falls back to settings.ADMISSIONS_SALES_EMAIL if blank.', max_length=254)),
                ('banner_bg_image', models.ForeignKey(blank=True, help_text='Recommended: 1920 × 486 px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='careers_banner_bg', to='wagtailimages.image', verbose_name='Banner Background Image')),
            ],
            options={
                'verbose_name': 'Careers Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CareerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('badge_type', models.CharField(choices=[('teaching', 'Teaching'), ('admin', 'Administration'), ('support', 'Support Staff')], default='teaching', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('employment_type', models.CharField(blank=True, default='Full-time', max_length=100)),
                ('qualification', models.CharField(blank=True, default='', max_length=200)),
                ('location', models.CharField(blank=True, default='On-site', max_length=200)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_positions', to='home.careerspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon_class', models.CharField(choices=[('fa-solid fa-graduation-cap', 'Graduation Cap'), ('fa-solid fa-book-open', 'Book Open'), ('fa-solid fa-book', 'Book Closed'), ('fa-solid fa-book-open-reader', 'Book Reader'), ('fa-solid fa-calculator', 'Mathematics'), ('fa-solid fa-flask', 'Chemistry / Lab'), ('fa-solid fa-atom', 'Physics / Atom'), ('fa-solid fa-microscope', 'Science Lab / Microscope'), ('fa-solid fa-dna', 'Biology / DNA'), ('fa-solid fa-bolt', 'Electricity / Electronics'), ('fa-solid fa-computer', 'Computer / IT'), ('fa-solid fa-laptop-code', 'Coding / Programming'), ('fa-solid fa-microchip', 'Robotics / Microchip'), ('fa-solid fa-language', 'Languages / English'), ('fa-solid fa-pen-nib', 'Urdu / Writing'), ('fa-solid fa-pen-to-square', 'Editing / Exams'), ('fa-solid fa-moon', 'Islamic Studies'), ('fa-solid fa-star-and-crescent', 'Islamic / Crescent'), ('fa-solid fa-flag', 'Pakistan Studies'), ('fa-solid fa-earth-asia', 'Geography / GK'), ('fa-solid fa-map', 'Social Studies / Map'), ('fa-solid fa-palette', 'Arts & Craft'), ('fa-solid fa-music', 'Music'), ('fa-solid fa-masks-theater', 'Drama / Theatre'), ('fa-solid fa-seedling', 'Early Years / Nursery'), ('fa-solid fa-child-reaching', 'Primary / Children'), ('fa-solid fa-person-running', 'Sports / PE'), ('fa-solid fa-futbol', 'Football'), ('fa-solid fa-basketball', 'Basketball'), ('fa-solid fa-table-tennis-paddle-ball', 'Table Tennis'), ('fa-solid fa-dumbbell', 'Gym / Fitness'), ('fa-solid fa-trophy', 'Trophy'), ('fa-solid fa-medal', 'Medal'), ('fa-solid fa-star', 'Star'), ('fa-solid fa-award', 'Award / Certificate'), ('fa-solid fa-ranking-star', 'Rankings / Top Scorer'), ('fa-solid fa-school', 'School Building'), ('fa-solid fa-chalkboard-user', 'Teacher / Lecture'), ('fa-solid fa-users', 'Students / Group'), ('fa-solid fa-user-graduate', 'Graduate Student'), ('fa-solid fa-user-tie', 'Principal / Admin'), ('fa-solid fa-people-group', 'Community / Assembly'), ('fa-solid fa-handshake', 'Partnership / Trust'), ('fa-solid fa-hands-holding-child', 'Child Support'), ('fa-solid fa-door-open', 'Admissions / Open Door'), ('fa-solid fa-file-pen', 'Exams / Test Paper'), ('fa-solid fa-file-circle-check', 'Application Approved'), ('fa-solid fa-clipboard-list', 'Checklist / Requirements'), ('fa-solid fa-clipboard-check', 'Verification / Check'), ('fa-solid fa-id-card', 'Student ID'), ('fa-solid fa-calendar-check', 'Events / Schedule'), ('fa-solid fa-calendar-days', 'Academic Calendar'), ('fa-regular fa-calendar', 'Calendar'), ('fa-solid fa-building-columns', 'Library / Hall'), ('fa-solid fa-utensils', 'Cafeteria / Canteen'), ('fa-solid fa-bus', 'School Transport'), ('fa-solid fa-kit-medical', 'Medical / First Aid'), ('fa-solid fa-shield-halved', 'Security / Discipline'), ('fa-solid fa-person-praying', 'Prayer Room'), ('fa-solid fa-camera', 'CCTV / Safety'), ('fa-solid fa-fire-extinguisher', 'Fire Safety'), ('fa-solid fa-water', 'Swimming Pool'), ('fa-solid fa-heart', 'Values / Character'), ('fa-solid fa-heart-pulse', 'Wellbeing / Health'), ('fa-solid fa-hand-holding-heart', 'Caring Environment'), ('fa-solid fa-lightbulb', 'Innovation / Ideas'), ('fa-solid fa-check-double', 'Quality Assurance'), ('fa-solid fa-circle-check', 'Verified / Certified'), ('fa-solid fa-bullhorn', 'Announcement'), ('fa-solid fa-bell', 'Notice / Alert'), ('fa-solid fa-envelope', 'Email / Letter'), ('fa-solid fa-phone', 'Phone / Contact'), ('fa-solid fa-comment-dots', 'Message / Chat'), ('fa-solid fa-check', 'Checkmark'), ('fa-solid fa-arrow-right', 'Arrow Right'), ('fa-solid fa-info-circle', 'Information'), ('fa-solid fa-question-circle', 'FAQ / Help'), ('fa-solid fa-link', 'Link / Resource')], default='fa-solid fa-heart-pulse', max_length=100)),
                ('icon_color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('pink', 'Pink / Red'), ('orange', 'Orange'), ('purple', 'Purple')], default='blue', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_benefits', to='home.careerspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('number', models.CharField(help_text='e.g. "50+", "98%", "1k+"', max_length=20)),
                ('label', models.CharField(help_text='e.g. "Faculty Members"', max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_stats', to='home.careerspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CareerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_steps', to='home.careerspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
