# Generated by Django 6.0.3 on 2026-07-04 20:10

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0048_newspage_banner_bg_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='boards_description',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='boards_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='boards_title',
        ),
        migrations.CreateModel(
            name='HomePageCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('campus_number', models.CharField(default='01', help_text='e.g. "01"', max_length=4)),
                ('tag', models.CharField(default='Campus One', help_text='Tag pill label, e.g. "Campus One"', max_length=60)),
                ('title', models.CharField(default='Main Campus\nAzeem School', help_text='Use a new line to split into two lines', max_length=200)),
                ('location', models.CharField(default='Gulshan-e-Iqbal, Karachi', max_length=200)),
                ('description', models.TextField(default='Our flagship campus is the heart of Azeem School.')),
                ('features', models.TextField(blank=True, help_text='One feature per line (up to 6 shown).\ne.g.\nAir-Conditioned Classrooms\nDigital Smart Boards')),
                ('years_count', models.CharField(blank=True, default='15+', help_text='e.g. "15+"', max_length=10)),
                ('years_label', models.CharField(blank=True, default='Years of Excellence', max_length=60)),
                ('cta_label', models.CharField(default='Explore Facilities', max_length=60)),
                ('cta_url', models.CharField(default='/facilities/', max_length=200)),
                ('image_bottom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Bottom Image (small)')),
                ('image_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Top Image (small)')),
                ('main_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Main Image (large)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_campuses', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BoardCard',
        ),
    ]
