# Generated by Django 6.0.3 on 2026-07-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0049_remove_homepage_boards_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecampus',
            name='title',
            field=models.TextField(default='Main Campus\nAzeem School', help_text='Use a new line to split into two lines'),
        ),
    ]
