# Generated by Django 6.0.3 on 2026-07-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_homepagecampus_title_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='campuses_heading',
            field=models.CharField(blank=True, default='Two Campuses, One Standard of Excellence', max_length=300, verbose_name='Main Heading'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='campuses_subheading',
            field=models.TextField(blank=True, default="Serving Karachi's families across two prime locations, each campus upholds the same commitment to quality education, dedicated faculty, and a nurturing environment.", verbose_name='Subheading / Description'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='campuses_tag',
            field=models.CharField(blank=True, default='Our Campuses', max_length=80, verbose_name='Section Tag (small label)'),
        ),
    ]
