# Generated by Django 6.0.3 on 2026-07-13 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_add_contact_campus'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='favicon',
            field=models.ForeignKey(blank=True, help_text='Upload a square PNG/ICO (recommended 512×512). Used as browser tab icon across all pages.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon'),
        ),
    ]
