# Generated by Django 6.0.3 on 2026-07-12 09:41

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_add_favicon_to_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactCampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('campus_name', models.CharField(default='Campus', max_length=100)),
                ('address', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('map_embed_url', models.URLField(blank=True, verbose_name='Google Maps Embed URL')),
                ('map_link_url', models.URLField(blank=True, verbose_name='Google Maps Link URL')),
                ('map_directions_url', models.URLField(blank=True, verbose_name='Get Directions URL')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_campuses', to='home.contactpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
