# Generated by Django 6.0.3 on 2026-07-13 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_add_homepage_favicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='testimonials_title',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
    ]
