# Generated by Django 6.0.3 on 2026-07-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_remove_homepage_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Parent / Guardian Name'),
        ),
    ]
