# Generated by Django 6.0.3 on 2026-07-15 10:22

from django.db import migrations


def remove_columns_if_exist(apps, schema_editor):
    from django.db import connection
    existing = {col.name for col in connection.introspection.get_table_description(
        connection.cursor(), 'home_admissionapplication'
    )}
    with connection.cursor() as cursor:
        if 'gender' in existing:
            cursor.execute("ALTER TABLE home_admissionapplication DROP COLUMN gender")
        if 'guardian_name' in existing:
            cursor.execute("ALTER TABLE home_admissionapplication DROP COLUMN guardian_name")


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_add_gender_guardian_safe'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(model_name='admissionapplication', name='gender'),
                migrations.RemoveField(model_name='admissionapplication', name='guardian_name'),
            ],
            database_operations=[
                migrations.RunPython(remove_columns_if_exist, migrations.RunPython.noop),
            ],
        ),
    ]
