# Generated by Django 6.0.3 on 2026-07-27 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_remove_gender_guardian_from_admission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='mv_bg_image',
            field=models.ForeignKey(blank=True, help_text='Optional. Shown behind the section instead of the default blue background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_mv_bg_image', to='wagtailimages.image', verbose_name='Mission & Vision Background Image'),
        ),
    ]
