# Generated by Django 6.0.3 on 2026-07-27 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_aboutpage_mv_bg_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicspage',
            name='grade_ladder_bg_image',
            field=models.ForeignKey(blank=True, help_text='Optional. Shown behind the grade ladder card instead of the default blue background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_grade_ladder_bg', to='wagtailimages.image', verbose_name='Grade Ladder Background Image'),
        ),
        migrations.AddField(
            model_name='academicspage',
            name='subjects_bg_image',
            field=models.ForeignKey(blank=True, help_text='Optional. Shown behind the subjects section instead of the default white background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academics_subjects_bg', to='wagtailimages.image', verbose_name='Subjects Section Background Image'),
        ),
    ]
