# Generated by Django 6.0.3 on 2026-07-27 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0059_academicspage_grade_ladder_bg_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitiespage',
            name='sports_bg_image',
            field=models.ForeignKey(blank=True, help_text='Optional. Shown behind the section instead of the default blue background.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities_sports_bg', to='wagtailimages.image', verbose_name='Sports & Athletics Background Image'),
        ),
    ]
