# Generated by Django 6.0.3 on 2026-07-27 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_facilitiespage_sports_bg_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='video_thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='about_video_thumbnail', to='wagtailimages.image', verbose_name='Video Thumbnail (shown if no video set)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='video_youtube_id',
            field=models.URLField(blank=True, help_text='Paste the full YouTube video URL — e.g. https://youtu.be/dQw4w9WgXcQ', verbose_name='Video URL'),
        ),
    ]
