# Generated by Django 6.0.3 on 2026-08-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0061_alter_aboutpage_video_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsgalleryphoto',
            name='category',
            field=models.CharField(blank=True, choices=[('events', 'Events'), ('sports', 'Sports'), ('activities', 'Activities'), ('achievements', 'Achievements'), ('celebrations', 'Celebrations')], default='events', max_length=20),
        ),
    ]
