# Generated by Django 6.0.3 on 2026-08-21 07:50

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0062_alter_newsgalleryphoto_category'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsgalleryphoto',
            name='category',
            field=models.CharField(blank=True, choices=[('events', 'Events'), ('sports', 'Sports'), ('arts', 'Arts'), ('campus', 'Campus'), ('academics', 'Academics')], default='events', max_length=20),
        ),
        migrations.CreateModel(
            name='NewsGalleryCategoryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('category', models.CharField(choices=[('events', 'Events'), ('sports', 'Sports'), ('arts', 'Arts'), ('campus', 'Campus'), ('academics', 'Academics')], default='events', help_text='Which filter pill this cover image belongs to', max_length=20)),
                ('image', models.ForeignKey(blank=True, help_text="Small cover image shown on this category's filter button (square works best)", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_gallery_category_image', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_gallery_category_images', to='home.newspage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
