# Generated by Django 6.0.3 on 2026-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0063_alter_newsgalleryphoto_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsgallerycategoryimage',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('sports', 'Sports'), ('arts', 'Arts'), ('campus', 'Campus'), ('academics', 'Academics'), ('activities', 'Activities'), ('celebrations', 'Celebrations')], default='events', help_text='Which filter pill this cover image belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='newsgalleryphoto',
            name='category',
            field=models.CharField(blank=True, choices=[('events', 'Events'), ('sports', 'Sports'), ('arts', 'Arts'), ('campus', 'Campus'), ('academics', 'Academics'), ('activities', 'Activities'), ('celebrations', 'Celebrations')], default='events', max_length=20),
        ),
    ]
