# Generated by Django 6.0.3 on 2026-09-16 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0064_alter_newsgallerycategoryimage_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='play_store_url',
            field=models.URLField(blank=True, default='', help_text='Link to the app\'s Google Play Store listing. Leave blank to hide the "Get the App" badge from the navbar.', max_length=500, verbose_name='Google Play Store URL'),
        ),
    ]
